### ISSUE TITLE
在ie9之下报错，对象不支持“scrollTo”属性或方法

### ISSUE THREAD

**Issue by yuan-xiaogang** [alvarotrigo/vue-fullpage.js#101]
![image](https://user-images.githubusercontent.com/29484071/53460015-944ae900-3a76-11e9-84de-f730ecbd44a6.png)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
We'll check it out!

**Comment by yuan-xiaogang** [comment]
Thanks

**Comment by alvarotrigo** [comment]
It can be due to the code you used in your vue application. 
Can you please provide an isolated reproduction of the issue in codesandbox or codepen?

**Comment by licong96** [comment]
I met him, too

**Comment by licong96** [comment]
Good again

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
