### ISSUE TITLE
bigSectionsDestination option causes maximum call stack size exceeded error

### ISSUE THREAD

**Issue by forethoughtde** [alvarotrigo/vue-fullpage.js#103]
Setting bigSectionsDestination: top causes vue-fullpage to throw maximum call stack size exceeded.

```
vue.esm.js:4458 Uncaught RangeError: Maximum call stack size exceeded
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
    at _traverse (vue.esm.js:2154)
```

[codesandbox.io Link](https://codesandbox.io/s/ry26l77mvn)

**Comment by alvarotrigo** [comment]
Your codesandbox doesn't work at all for me?
Shows the following error:
<img width="695" alt="Screenshot 2019-03-12 at 12 37 03" src="https://user-images.githubusercontent.com/1706326/54197252-bf482a80-44c3-11e9-98b5-a3cd00601726.png">


In any case, `bigSectionsDestination ` seems to be working fine for me on the codepen:
https://codepen.io/alvarotrigo/pen/LazvNB

Can you provide a reproduction in that codepen?

**Comment by alvarotrigo** [comment]
Oh I see... you forgot the quotes:


```javascript
        bigSectionsDestination: top,
```  

vs 

```javascript
        bigSectionsDestination: 'top',
```  

Remember it is a string value.
