### ISSUE TITLE
Line between pages -.-

### ISSUE THREAD

**Issue by EnzoBatista** [alvarotrigo/vue-fullpage.js#104]
Hi, there's anyone who see a line between pages too?

**Comment by alvarotrigo** [comment]
Do you see lines in the [provided codepen](https://codepen.io/alvarotrigo/pen/zpQmwq)?

**Comment by EnzoBatista** [comment]
There's a kind of gradient or something between pages when transition happen. 
I will check out my code again, maybe i'm doing something wrong, or need new eye glasses.

Thank you for answer

**Comment by alvarotrigo** [comment]
I'm not quite sure if you answered my question. 
Was it an answer to it or just an explanation of your issue?

Could you please let me know if you see that same behaviour on the codepen i mentioned?

**Comment by EnzoBatista** [comment]
If you putt the same background color in two consecutive pages there is a line between or something, that's what i mean

**Comment by alvarotrigo** [comment]
Not really?
https://codepen.io/alvarotrigo/pen/EMeBmm

It seems it is your own CSS the one who's adding the margin.
I'll close the issue until proven the opposite.
