### ISSUE TITLE
Vue component is not replaced with template when using nuxt generate

### ISSUE THREAD

**Issue by ramiroazar** [alvarotrigo/vue-fullpage.js#105]
The `<full-page>` component is not replaced with `<div>` element in the [template](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/src/FullPage.vue) when running `nuxt generate`.

This can be replicated with a basic setup following [instructions](https://nuxtjs.org/guide/installation) for Nuxt.js and [instructions](https://github.com/alvarotrigo/vue-fullpage.js#usage-with-nuxtjs) for Vue-fullpage.js and running `nuxt generate`.

The `<full-page>` component is rendered correctly if just running `nuxt` in `universal` mode, so it works fine during development.

The `<full-page>` component is also rendered correctly if running `nuxt generate` while nesting the component in a `<no-ssr>` component, but as described in the installation instructions, this has negative SEO implications.

Node.js `v10.15.3`
Nuxt.js `v2.6.1`
Vue-fullpage.js `v0.1.2`

**Comment by dobromir-hristov** [comment]
That's pretty much expected. It won't work in generate, as that again is a server rendered env, so no "window" for example.

**Comment by ramiroazar** [comment]
That's correct, not setting `ssr: false` would lead to errors due to references to `window` and setting it leads to the component not getting rendered correctly on the server. The issue I attempted to describe is not that the component isn't rendered correctly on the server side, but rather that it's not rendering correctly on the client side, even after the application has been hydrated.

**Comment by ramiroazar** [comment]
![Screen Shot 2019-04-11 at 2 45 49 pm](https://user-images.githubusercontent.com/3581503/55931407-a10f4f00-5c68-11e9-8b5c-d4c0e113ed15.png)

Just to clarify this issue, the above is a screenshot of Chrome DevTools inspecting a client side hydrated application created using `create-nuxt-app` and generated using `nuxt generate` with no additional dependencies besides `vue-fullpage.js`.

**Comment by alvarotrigo** [comment]
@ramiroazar i guess what's definetely wrong there is the `options=[ojbect Object]` part. The rest seems to be ok?

**Comment by ramiroazar** [comment]
That's right, @alvarotrigo, though I think the `options` attribute is just a side effect of the `<full-page>` template not getting rendered.

Ideally, setting `ssr: false` would prevent fatal errors during generation, partially render the component on the server side and fully render the component on the client side.

However, despite _fullPage.js_ being initialized, the component isn't rendering correctly on the client side, as seen in the screenshot above.

As <full-page> is not a valid HTML element, this is leading to some layout issues, which can at least be worked around with a shim and CSS.

Due to how static generation works in _Nuxt.js_, this issue only happens on first load and not when navigating within the application using `vue-router` to a page containing the component.

**Comment by alvarotrigo** [comment]
Any idea why this can be happening @dobromir-hristov @Chiaparini  @vaso2?

**Comment by dobromir-hristov** [comment]
I need to give it a test, but I think I know why.

**Comment by dobromir-hristov** [comment]
Asked Nuxt core team, will give more info when I have.

**Comment by alvarotrigo** [comment]
@dobromir-hristov thanks! 👍

**Comment by MeChesto** [comment]
Has the problem been solved?I have the same problem.

**Comment by alvarotrigo** [comment]
@MeChesto not yet, the issue stills open :)

**Comment by vaso2** [comment]
By the way, I think it's the same problem, why component doesn't work with SSR

**Comment by CHEWX** [comment]
Has there been any progress on this? Or any workarounds.

**Comment by alvarotrigo** [comment]
> Asked Nuxt core team, will give more info when I have.

@dobromir-hristov managed to get any insights into it?

**Comment by ramiroazar** [comment]
I ended up working around this issue by using `fullpage.js` instead of `vue-fullpage.js`.

I included `fullpage.js` as a [plugin](https://nuxtjs.org/guide/plugins) with `ssr: false` and used it according to the [documentation](https://github.com/alvarotrigo/fullPage.js).

This seemed to work as expected both client and server side.

**Comment by CHEWX** [comment]
That’s interesting, thanks @ramiroazar 

Would you say this is a viable workaround @alvarotrigo - my oversight of this issue is holding back a go-live. Not entirely sure what features I will miss with this approach, if any at all.

**Comment by alvarotrigo** [comment]
@Chiaparini @vaso2 @ebisbe if you can help with this issue that'd be great! Any insights or tips for directions will be appreciated too! 👍

**Comment by jwoodmansey** [comment]
So I managed to figure out a bit of a work around for this. You can force nuxt to re-render after the client loads by using a client-only and `slot="placeholder"`.

```
    <client-only>
      <full-page id="fullpage" class="fullpage" :options="options">
          <!-- Pages component -->
      </full-page>
      <full-page id="fullpage" slot="placeholder" class="fullpage" :options="options">
          <!-- Pages component -->
      </full-page>
    </client-only>
```

Not pretty but it does seem to work nicely allowing the pages to be pre-render. 

Since the content appears the same there is also no flash. You may have to re-implement some of the styles that fullpage applies, I had to re-create `fp-tableCell` and `fp-table` styles on the page content to get it exactly the same, this will likely vary based on your use case:

```
.fp-tableCell {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  width: 100%;
}
.section.fp-table {
  display: table;
  table-layout: fixed;
  width: 100%;
  height: 100vh;
}
```

**Comment by alvarotrigo** [comment]
@jwoodmansey thanks for the tip!! 
Do you think we could implement this fix somehow within the component itself? 

> Since the content appears the same there is also no flash. You may have to re-implement some of the styles that fullpage applies, I had to re-create `fp-tableCell` and `fp-table` styles on the page content to get it exactly the same, this will likely vary based on your use case:

Perhaps you mean these ones?
I wouldn't play much with `flex` and I would use the ones fullPage.js uses instead :)

```css
#fullpage,
.section,
body,
.fp-tableCell,
html {
    height: 100%
}
```
Assuming #fullpage is your fullpage wrapper and that you use the default selectors for sections and slides.

**Comment by jwoodmansey** [comment]
I'm not sure, I had tried out https://github.com/vaso2/fullpage-nuxt expecting it to do something like this, but this issue is the same on there.

> I wouldn't play much with flex and I would use the ones fullPage.js uses instead :)

Ah yes thanks, that must be specific to our structure!

**Comment by vaso2** [comment]
@jwoodmansey I tried different approaches to solve this problem, and your's new one. I'll test it and integrate with the plugin if possible

**Comment by lhoucinecherif** [comment]
still having the same issue in gridsome!

**Comment by SupriyaGo** [comment]
I am getting the same issue
