### ISSUE TITLE
Fullpage Build with dragAndMove plugin scrolls to top

### ISSUE THREAD

**Issue by adivohayon** [alvarotrigo/vue-fullpage.js#108]
**View only in mobile**
https://alinecohen.storystore.co.il/

To reproduce, try selecting a color, scroll down and select another color. This causes fullpage to scroll up to the first section. Also, performance starts to drop.

I rebuild fullpage every time someone chooses a color (as the images and the number of images change). I also rebuild after I add new sections (not seen in the example, but the problem is the same).
I'm using the following options for fullpage:
```
	sectionSelector: '.shelf',
	slideSelector: '.slide',
	autoScrolling: true,
	licenseKey: 'YYYYYYYYYYYYY',
	dragAndMoveKey: 'XXXXXXXXXXXX',
	dragAndMove: true,
	controlArrows: false,
	slidesNavigation: true,
```

After some debugging I noticed that after the first rebuild the afterLeave event fires multiple times. I debounce it for performance but it seems odd that it only happens after I rebuild. I also noticed that if I disable drag and move it works well, so I highly suspect it has something to do with the dragAndMove plugin.

Any ideas on how to fix this?

**Comment by alvarotrigo** [comment]
We do not check specific websites or use cases, only isolated reproductions.

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
