### ISSUE TITLE
Uncaught ReferenceError: IScroll is not defined

### ISSUE THREAD

**Issue by exctac** [alvarotrigo/vue-fullpage.js#110]
Hey. 

I connect the script to my project in main.js:

```js
import Vue from 'vue'
import 'fullpage.js/vendors/scrolloverflow'
import VueFullPage from 'vue-fullpage.js/dist/vue-fullpage.js'
import App from './App.vue'
Vue.use(VueFullPage)

new Vue({
  store, axios,
  render: h => h(App)
}).$mount('#app');
```

Then I collect the whole project:
`npm run build`

When I open a web page in the console error:

Uncaught ReferenceError: IScroll is not defined
    at scrolloverflow.js:2148
    at scrolloverflow.js:2143
    at Object.a0a0 (scrolloverflow.js:2142)
    at r (bootstrap:78)
    at Module.56d7 (s-settings.svg:1)
    at r (bootstrap:78)
    at Object.0 (bootstrap:151)
    at r (bootstrap:78)
    at e (bootstrap:45)
    at bootstrap:151

what am I doing wrong? or is it a bug of some kind?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [Codepen](https://codepen.io/alvarotrigo/pen/zpQmwq), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by exctac** [comment]
by the way, if I run ` npm run serve`, everything works

**Comment by alvarotrigo** [comment]
We will keep waiting for the isolated reproduction :)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
