### ISSUE TITLE
Scrolloverflow with nuxt ssr

### ISSUE THREAD

**Issue by ZerNico** [alvarotrigo/vue-fullpage.js#117]
I currently have the issue that scrolloverflow doesn't work if the fullpage component isn't wrapped inside no-ssr.
It works when running the dev server but in production mode I am not able to scroll to any other section.
Maybe that's a limitation with using scrolloverflow but I hope there is some way around it with using SSR, cause the no-ssr option would defeat the purpose of using nuxt in the first place as SEO will suffer.

**Comment by alvarotrigo** [comment]
Can you provide us with a reproduction of the issue somewhere?

Also, can you post the exact code you are using for it? Both, HTML and JS ?

**Comment by ZerNico** [comment]
Reproducing it in codepen or similar will not really work cause it's an issue with nuxt and SSR but I could send you the link to a github repo with the issue.

**Comment by alvarotrigo** [comment]
@ZerNico just post here the relevant code for the reproduction. Keep it as small as possible to avoid distractions or 3rd party errors. 

Also, can you provide a link to a URL so we can check the result in it?

**Comment by ZerNico** [comment]
Here is a github repo with just the relevant code:
https://github.com/ZerNico/scrolloverflow-bug
(The most relevant is probably plugins/fullpage.js and pages/index.vue)

I can't really host the page atm as I am on vacation but if you need it I can do that in a few days. 
(tho I guess you can just build and start it from the github repo)

Thanks alot for your help

**Comment by alvarotrigo** [comment]
> @ZerNico can you please just post here the relevant code for the reproduction. Keep it as small as possible to avoid distractions or 3rd party errors.

**Comment by alvarotrigo** [comment]
> I can't really host the page atm as I am on vacation but if you need it I can do that in a few days.
> (tho I guess you can just build and start it from the github repo)

No rush :)

**Comment by ZerNico** [comment]
@alvarotrigo Here is the resulting page of the bug https://bug.zernico.de/

And these are the relevant parts

`
import 'fullpage.js/vendors/scrolloverflow.min'

import Vue from 'vue'
import VueFullPage from 'vue-fullpage.js'

Vue.use(VueFullPage)
`

`<template>
  <div>
    <full-page ref="fullpage" :options="options" id="fullpage">
      <div class="section">
        Home ...
      </div>
      <div class="section">
        Features ...
        <h1>123</h1>
        
      </div>
      <div class="section">
        Team ...
      </div>
      <div class="section">
        Changelog ...
      </div>
      <div class="section">
        Download ...
      </div>
    </full-page>
  </div>
</template>

<script>
export default {
  data() {
    return {
      options: {
        anchors: ['home', 'features', 'team', 'changelog', 'download'],
        sectionsColor: ['#ffffff', '#4285f4', '#db4437', '#ffffff', '#4285f4'],
        navigation: true,
        scrollOverflow: 'true'
      }
    }
  }
}
</script>`

**Comment by alvarotrigo** [comment]
@dobromir-hristov @Chiaparini any idea what can be the cause?

**Comment by alvarotrigo** [comment]
@vaso2 any idea what can be the reason?

**Comment by DmitriyColors** [comment]
@ZerNico The only option is to use this setting nuxt.config.js
In principle, as with most plugins Vue! 
`
  */
  plugins: [
    { src: '~plugins/responsive.js', mode: 'client'},
    { src: '~plugins/vue-screen-size.js', mode: 'client'},
    { src: '~plugins/fontawesome.js' },
    { src: '~plugins/vue-js-modal.js' },
    { src: '~plugins/map.js' },
    { src: '~plugins/vue-fullpage.js', mode: 'client'}
  ],
  /*
`

**Comment by DmitriyColors** [comment]
@ZerNico The only option is to use the following `nuxt.config.js` setting
```  
plugins: [
    { src: '~plugins/responsive.js', mode: 'client'},
    { src: '~plugins/vue-screen-size.js', mode: 'client'},
    { src: '~plugins/fontawesome.js' },
    { src: '~plugins/vue-js-modal.js' },
    { src: '~plugins/map.js' },
    { src: '~plugins/vue-fullpage.js', mode: 'client'}
  ],
```

**Comment by DmitriyColors** [comment]
@ZerNico , @alvarotrigo I'm sorry. And what is not suitable for this decision?
[Plagin documetation ](https://github.com/alvarotrigo/vue-fullpage.js#using-a-nuxt-fullpagejs-plugin)

**Comment by ZerNico** [comment]
@DmitriyColors how does your vue-fullpage.js plugin look like?
Because that code doesn't fix anything for me

**Comment by alexguevara** [comment]
I guess you should add to your styles:

```
.fullPage {
  display: block;
}
```

**Comment by versionmj** [comment]
@ZerNico I am having the same issue.  Have you found a solution?

**Comment by JuniorMeza** [comment]
I found the solution by adding as an external library in nuxt.config.js and removing the plugins

script: [{
      src: 'https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.8/vendors/scrolloverflow.js'
    }]

**Comment by BlackBiM123** [comment]
@ZerNico  @versionmj 
I have this problem too, and im totally confused with it. please. tell me that the problem is already solved? and if not what solution you find

**Comment by alvarotrigo** [comment]
For SSR we will soon merge this pull request, so you can take a look at this solution:
https://github.com/alvarotrigo/vue-fullpage.js/pull/161

**Comment by BlackBiM123** [comment]
@alvarotrigo Im sorry  for perseverance but could you tell mу more precisely how soon you will merge it? I'm looking forward to this fix, but can't fix it by myself according to your solution. It gives me only new errors, i suppose i do something wrong, so i need a tutorial or something like that.

**Comment by alvarotrigo** [comment]
Unfortunately I do not have a precise time in mind. I'll talk with Dobromir and see if he's available these days.

If you are in a rush,  please consider getting [a Business License for it](https://alvarotrigo.com/fullPage/pricing/) and we'll move it into the high priority list.

**Comment by BlackBiM123** [comment]
@alvarotrigo ok. understood.Yes, im in a rush but...  The main thing I'm interested in, is the guarantee of properly working fullpage with SSR on production. If you can fix it soon i will buy the buisness license of course, but .. the problem apppeared quite a long time ago, thats why i doubt. I will not use this plugin without this feature. What can you say about this?

**Comment by alvarotrigo** [comment]
@BlackBiM123 I can't promise a solution because we can't assure things 100%, but I can promise we can take a look at the issue and potentially find a solution :)

Priority support doesn't mean we will solve things for sure. It means we will move you to the high priority tasks and we will do our best to provide a solution to them. Unfortunately sometimes there are problems that do not have a solution or the provided solution doesn't fit everybody's use case. 

We will spend the time required to implement Dobromir pull request into the main branch. He said he managed to make it work and provided a repository with the suggested solution. So let's hope he's not wrong :)
