### ISSUE TITLE
navigation dot not show

### ISSUE THREAD

**Issue by subdance** [alvarotrigo/vue-fullpage.js#118]
```javascript
<template>
  <div id='main-body'>
    <full-page ref="fullpage" :options='options' id="fullpage">
      <div class="section">
        aaa
      </div>
      <div class="section">
        sss
      </div>
    </full-page>
  </div>
</template>

<script>
export default {
  name: 'home',
  components: {
  },
  data() {
    return {
      options: {
        navigation: true,
      },
    }
  },
}
</script>
```
That's all the code. Page.js works fine and the scroll effect is awesome, but the navigation dot didn't show.I don't see where went wrong.

**Comment by alvarotrigo** [comment]
Perhaps you are forgetting to add the CSS file?

```js
import 'fullpage.js/dist/fullpage.css'
``` 

See the [demos folder](https://github.com/alvarotrigo/vue-fullpage.js/tree/master/demos) and compare with your project.

**Comment by subdance** [comment]
@alvarotrigo yes, after adding this import it works. Thank you.
