### ISSUE TITLE
Export "default" was not found in 'vue-fullpage.js'

### ISSUE THREAD

**Issue by laurentbch** [alvarotrigo/vue-fullpage.js#119]
Dear all,

I start a new project using nuxt and vue-fullpage.js.
Following those instructions : https://github.com/alvarotrigo/vue-fullpage.js#usage-with-nuxtjs
I have defined my own plugin : 
- Create a fullpage.js file 
- Update nuxt.config.js file to include the plugin and init it before mounting the app.

Note : I do not use 'nuxt-fullpage.js' dependencies.

I restart my nuxt project on dev mode and get :
- 1 warn on terminal log : 
` in ./plugins/fullpage.js
"export 'default' (imported as 'Fullpage') was not found in 'vue-fullpage.js' ` 
- 1 error on browser console log 
`Uncaught TypeError: Cannot set property 'VueFullpageJs' of undefined`

I remove node_modules folder and perform a new install but still do not works.

Nuxt version : 2.8.1
vue-fullpage.js : 0.1.3

What do I miss ?
I have using other plugin, I have perform a test following those instructions https://nuxtjs.org/guide/plugins and include vue-notification plugin and it works well for this plugin.

Thanks,

**Comment by alvarotrigo** [comment]
@dobromir-hristov, @vaso2 any clue?

**Comment by dobromir-hristov** [comment]
Eh this should not happen. Can you do a codesandbox or something to see whats wrong?

**Comment by vaso2** [comment]
@laurentbch  I recommend you just start using `nuxt-fullpage.js` - it makes just what is needed and in the right way, no overhead.

**Comment by alvarotrigo** [comment]
Closed due to lack of isolated reproduction.
