### ISSUE TITLE
Nuxt.js SSR Firefox

### ISSUE THREAD

**Issue by Moldieman** [alvarotrigo/vue-fullpage.js#120]
Hi @alvarotrigo, 

I have managed to build my site using Nuxt SSR successfully with everything working and no errors. However Firefox seems to be the only browser that is giving me issues. 

If navigating around the site `fullpage` seems to start working again but I can't figure out why. Any ideas or help will be appreciates.

It seems that running the project in dev mode with ```npm run dev``` works 100% in Firefox but when compiling the project with ```npm run build``` things break. Must be a compiling issue?

**Comment by alvarotrigo** [comment]
Hey @Moldieman!

Unfortunately I do not check websites, only isolated reproductions. This makes it easier for both.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
