### ISSUE TITLE
Some part of the section is nested in next section 

### ISSUE THREAD

**Issue by aicsoft115** [alvarotrigo/vue-fullpage.js#123]
Hello

Thanks for your component.
I am using your fullpage package in my Vuetify app and there is a section that contains long dynamic content.
I set scrollOverflow option as true, but that some of section's content is shown in the next section.
So I can't scroll to the end in the section.
Would you tell me the way to resolve this?

Cheers

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by aicsoft115** [comment]
Hi, thanks for your quick reply.

Could I tell you the steps of my issue here?

- App.js
  <template>
     <div id="app">
       <v-app>
         <app-header></app-header>
         <router-view/>
        </v-app>
     </div>
  </template>
- Home.vue(first route component)
  <template>
    <full-page ref="fullpage" :options="options" id="fullpage">
      <div class="section" id="home_section">...</div>
      <section1-app></section1-app>
      <section2-app></section2-app>
      <app-footer></app-footer> 
    </full-page>
  </template>
- section1-app, section2-app and app-footer components are something like the below:
  <template>
    <div class="section">
      ...
    </div>
  </template>
- package.json
    "vue": "^2.5.2",
    "vue-fullpage.js": "^0.1.1",
    "vue-router": "^3.0.1",
    "vue-spinner": "^1.0.3",
    "vue-visible": "^1.0.2",
    "vue2-animate": "^2.0.0",
    "vue2-smooth-scroll": "^1.0.3",
    "vuetify": "^1.3.7",
    "vuex": "^3.0.1",
    "webpack-bundle-tracker": "^0.3.0"

home_section, section1-app pages are working well as I expected.
But section2-app has long content(dynamic) and third page for it isn't scrolled to the end of content.
Last part of it's content is shown at the top of the app-footer section.
So, I can't scroll to the end of the section2.
I tried with static long content, but failed.
Could you help me with this?

**Comment by aicsoft115** [comment]
Hi, sorry for my mistake.

Home.vue(first route component)
```
<template>
    <full-page ref="fullpage" :options="options" id="fullpage">
      <div class="section" id="home_section">
        ...
      </div>
    <section1-app></section1-app>
    <section2-app
      @rebuild="rebuildFullPage()">
    </section2-app>
    <app-footer></app-footer>
  </full-page>
</template>
```
section1-app, section2-app and app-footer components are something like the below:
```
<template>
  <div class="section" id="xxx">
  ...
  </div>
</template>
```
package.json
"vue": "^2.5.2",
"vue-fullpage.js": "^0.1.1",
"vue-router": "^3.0.1",
"vue-spinner": "^1.0.3",
"vue-visible": "^1.0.2",
"vue2-animate": "^2.0.0",
"vue2-smooth-scroll": "^1.0.3",
"vuetify": "^1.3.7",
"vuex": "^3.0.1",
"webpack-bundle-tracker": "^0.3.0"

home_section, section1-app pages are working well as I expected.
But section2-app has long content(dynamic) and third page for it isn't scrolled to the end of content.
Last part of it's content is shown at the top of the app-footer section.
So, I can't scroll to the end of the section2.
I tried with static long content, but failed.
Could you help me with this?

**Comment by alvarotrigo** [comment]
Can you please use codepen or codesandbox? Thanks!

**Comment by aicsoft115** [comment]
I have some trouble for using codepen.
Could I share my repo with you?

**Comment by alvarotrigo** [comment]
Sorry I do not check repos unless you got the Organization license.

**Comment by aicsoft115** [comment]
I have license key for vue-fullpage.

**Comment by alvarotrigo** [comment]
If you have the [organisation one](https://alvarotrigo.com/fullPage/pricing/), please let me know the license key:

**Comment by aicsoft115** [comment]
How can I show you my license key?
Can I show it here?
Or can I send it to your email address?

**Comment by alvarotrigo** [comment]
You can [contact me](https://alvarotrigo.com/#contact) and sent it there.

**Comment by aicsoft115** [comment]
I sent you an email.
