### ISSUE TITLE
Classes are being added too early

### ISSUE THREAD

**Issue by CHEWX** [alvarotrigo/vue-fullpage.js#129]
### Description

Class names are being added to the DOM too early, so previous route gets them.

See screenshot. Fullpage.js is only on the INDEX. But the class names are being added to the previous route and then INDEX wipes.

This screenshot is simply landing on INDEX clicking CONTACT route and then back to INDEX.

![Screenshot 2019-07-24 at 08 28 48](https://user-images.githubusercontent.com/5207147/61773667-26b8a400-aded-11e9-9fcb-9e664b83e1ba.png)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Could you please provide an isolated reproduction of the issue in codesandbox so we can see what you mean?

**Comment by CHEWX** [comment]
Sure — https://7fvj9.sse.codesandbox.io/

You'll see `fp-viewing-0` displays on first load, but not subsequent routes.

**Comment by alvarotrigo** [comment]
Expected result and current result?

Can we get the link to the editable codesandbox too?

**Comment by CHEWX** [comment]
https://codesandbox.io/s/codesandbox-nuxt-7fvj9 — this link?

I'm expecting to see `.fp-viewing-0` on `afterLoad` callback.

**Comment by alvarotrigo** [comment]
> https://codesandbox.io/s/codesandbox-nuxt-7fvj9 — this link?

Yes thanks!
I'll take a look at it!

**Comment by CHEWX** [comment]
There is also odd behaviour in the front-end link if you open up console, look at the route and then look at the output.

**Comment by alvarotrigo** [comment]
> I'm expecting to see .fp-viewing-0 on afterLoad callback.

And what do you see?

What are the steps to reproduce the issue?
Scroll down to the 2nd section and click on "here"?

**Comment by CHEWX** [comment]
Click console.

Click first "here", will take from INDEX to FULLPAGE.

FULLPAGE will have no class. Scroll down and it will now show the class. Click HERE again to go back to INDEX. INDEX will have no class.

Wherever I see no class, I'm expecting to see a class?

**Comment by alvarotrigo** [comment]
So, basically you say that the `afterLoad` callback fires before the route changes. 
This way, when do `document.body.classList` within the `afterLoad` callback, you still get the classes applied to the body element before the route changes, right?

I believe this might be related with this issue https://github.com/alvarotrigo/vue-fullpage.js/issues/81 and the transition that takes place when changing from one route to another one.

@vaso2 any idea how could we deal with this?
