### ISSUE TITLE
Question about demo

### ISSUE THREAD

**Issue by TheCodeClown** [alvarotrigo/vue-fullpage.js#13]
I was hoping someone could help clear up my confusion. The demo that comes with this package when downloading through npm (demo1) does not react to my changes. I keep changing things in the DemoApp.vue expecting it to be reflected in the vue component when viewing the dist/index.html but testing the demo page continues to reveal the same content. How do I change the demo's slide content?

**Comment by alvarotrigo** [comment]
You need to build them using npm:

```shell
npm run-script demo1
```
