### ISSUE TITLE
Uncaught DOMException: Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by chasegiunta** [alvarotrigo/vue-fullpage.js#130]
### Description
Getting this error randomly, seemingly stemming from scrolloverflow.js, but only _sometimes_ as if it's some sort of race condition.

This is a webpack build, looking like so in my main.js as per the README.
```
import Vue from 'vue'
import 'fullpage.js/vendors/scrolloverflow'
import VueFullPage from 'vue-fullpage.js'
Vue.use(VueFullPage)
```

```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in response to a mutation?
    at Object.ao [as wrapInner] (webpack-internal:///./node_modules/vue-fullpage.js/dist/vue-fullpage.js:98:3045)
    at createScrollBar (webpack-internal:///./node_modules/fullpage.js/vendors/scrolloverflow.js:2288:38)
    at eval (webpack-internal:///./node_modules/fullpage.js/vendors/scrolloverflow.js:2320:25)
    at NodeList.forEach (<anonymous>)
    at forEachSectionAndSlide (webpack-internal:///./node_modules/fullpage.js/vendors/scrolloverflow.js:2312:32)
    at scrollBarHandler.createScrollBarForAll (webpack-internal:///./node_modules/fullpage.js/vendors/scrolloverflow.js:2240:21)
    at ge (webpack-internal:///./node_modules/vue-fullpage.js/dist/vue-fullpage.js:98:17653)
    at Ee (webpack-internal:///./node_modules/vue-fullpage.js/dist/vue-fullpage.js:98:19522)
```

### Link to isolated reproduction with no external CSS / JS
I can't actually reproduce this in codesandbox, as it seems it's a matter of potentially something loading or initiating before something else, and happens randomly, so I'm simply submitting in case you're able to hint down what it could possibly be with that stack pasted above.

Understandable if you can't offer a fix, but figured I'd toss it your way in case you guess something due to stack error above.

### Steps to reproduce it
1. Implement vue-fullPage.js in webpack build
2. Ensure you're importing scrolloverflow.js addon
3. Load page... repeatedly

### Versions
fullpage 3.0.7
vue-fullpage 0.1.4
Chrome 76 on MacOS 10.14.5 (though have only noticed it so far on Chrome while emulating a device - iPhone X - and client observed it natively on their Galaxy S8 in Chrome)

**Comment by chasegiunta** [comment]
Also want to note, that when this error is thrown, the `onLeave` event is no longer being emitted.

**Comment by chasegiunta** [comment]
Eh, this has something to do with attempting to load a YouTube iframe within a scrolloverflow section, and if I had to guess, scrolloverflow is having trouble getting height of the section while the iframe loads. This disappears when removing the youtube iframe embed completely.

**Comment by chasegiunta** [comment]
Looks like I've been able to prevent this bug by delaying the iframe insertion via timeout into the scrolloverflow section by 1000ms.

**Comment by alvarotrigo** [comment]
Any idea what can this be @dobromir-hristov, @vaso2 ?

>    at eval (webpack-internal:///./node_modules/fullpage.js/vendors/scrolloverflow.js:2320:25)

There's nothing in line 2320 of scrolloverflow.js

https://github.com/alvarotrigo/fullPage.js/blob/3.0.7/vendors/scrolloverflow.js#L2320

>     at Object.ao [as wrapInner] (webpack-internal:///./node_modules/vue-fullpage.js/dist/vue-fullpage.js:98:3045)

Nothing either in line 98 of vue-fullpage.js

https://github.com/alvarotrigo/vue-fullpage.js/blob/master/dist/vue-fullpage.js#L98
