### ISSUE TITLE
parallax and nuxt

### ISSUE THREAD

**Issue by gen4sp** [alvarotrigo/vue-fullpage.js#132]
### Description
Full-page works fine, 
- I've added empty div fp-bg with a background picture.
- I've bought FP license and Parallax license
-  but parallax doesn't work.

Does it work with standard nuxt plugin? 
How it should be inited properly? 
Thank you!

**Comment by dobromir-hristov** [comment]
Could you give a minimal reproduction repo? Would be easier for us and @alvarotrigo to give you help.
Thanks :)

**Comment by gen4sp** [comment]
unfortunately, not now.
But question is, there are no special steps required to make it work? 
there is an instruction 
```
Extensions requires you to use the minified file fullpage.extensions.min.js that is inside the dist folder instead of the usual fullPage.js file (fullpage.js or fullpage.min.js).
```
Should I follow it with vue-fullpage as well? How to do it properly, if yes? 
Thank you!

**Comment by alvarotrigo** [comment]
@dobromir-hristov thanks for your support!

@gen4sp, there are no special steps besides the ones detailed here [in the docs](https://github.com/alvarotrigo/vue-fullpage.js#bundler-webpack-rollup) regarding importing the extension file.

Vue-fullpage.js uses `fullpage.extensions.min.js` by default so you won't have to worry about it.

On the [webpack example](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/demos/webpack/src/main.js) you can see how we could import the `scrollHorizontally` extension. The line is commented:

https://github.com/alvarotrigo/vue-fullpage.js/blob/b8904eab3d8fcd085f1eb4a7bcc434a3f52f1e97/demos/webpack/src/main.js#L3-L10

**Comment by alvarotrigo** [comment]
> * but parallax doesn't work.

What do you mean by that? 
Have you followed the structure you can find in the `example-parallax.html` file that comes with the download of the extension?
Have you checked the [parallax docs](https://github.com/alvarotrigo/fullPage.js/wiki/Extension---Parallax)?
