### ISSUE TITLE
Slides not working

### ISSUE THREAD

**Issue by sergkif** [alvarotrigo/vue-fullpage.js#136]
Slide is not working. Tryin to add slides to the section.

[Here is the code](https://github.com/sergkif/Toast-Cafe/blob/master/src/App.vue)

Vue version: 3.7.0
vue-fullpage.js version: 0.1.4

All useful info you can find on my [repo](https://github.com/sergkif/Toast-Cafe)

Thank you for your help :)

**Comment by sergkif** [comment]
That's how it looks, so link changes but the content is the same. And all the slides are on the other sections. 

![image](https://user-images.githubusercontent.com/6279738/64981375-eecc5b00-d889-11e9-91f8-771e77554b66.png)

![image](https://user-images.githubusercontent.com/6279738/64981435-0a376600-d88a-11e9-98ba-e6fd2cead8b6.png)

![image](https://user-images.githubusercontent.com/6279738/64981462-16bbbe80-d88a-11e9-992a-8cf9249a4319.png)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed due to lack of isolated reproduction.
