### ISSUE TITLE
Vue-fullpage is not working with SSR Nuxt

### ISSUE THREAD

**Issue by alexguevara** [alvarotrigo/vue-fullpage.js#137]
### Description
When building Nuxt in production with default setup, vue-fullpage breaks on any dom change.

### Link to isolated reproduction with no external CSS / JS
https://github.com/alexguevara/fp-nuxt-issue

### Steps to reproduce it
1. npm run build
2. npm run start
3. Click on the button on the hero section

It seems that on every dom change fullpage removes its classes from section elements.
This happens only on production build.
See video for details:
https://www.loom.com/share/45ee7ef8a6c84550a65cb85246e81cd7

### Versions 
vue-fullpage.js: ^0.1.4
nuxt: 2.9.2

### UPDATE: the problem is caused by SSR.
Using `<no-ssr>` fixes the issue, but we then loose SEO so this is not a solution.

And we have this when using SSR wich is not correct I think
![image](https://user-images.githubusercontent.com/7500019/66846161-0f1b3280-ef7a-11e9-98cd-9bb1f33ae8c1.png)

**Comment by alvarotrigo** [comment]
Did you read how to use it with nuxt?
https://github.com/alvarotrigo/vue-fullpage.js#usage-with-nuxtjs

**Comment by alvarotrigo** [comment]
> This happens only on production build.

Not on dev environment?

**Comment by alexguevara** [comment]
Yes< only in production and I`m absolutely stuck with it

**Comment by alvarotrigo** [comment]
Sounds like a server configuration issue?
I guess I won't be able to reproduce it in my computer then?

**Comment by alvarotrigo** [comment]
Try asking in the nuxt plugin's repository:
https://github.com/vaso2/nuxt-fullpage.js

**Comment by alexguevara** [comment]
You can reproduce it by downloading the repo and following steps described above.
Its a default nuxt setup

**Comment by alvarotrigo** [comment]
Try asking in the nuxt plugin's repository which is maintained by @vaso2 :
https://github.com/vaso2/nuxt-fullpage.js

**Comment by alvarotrigo** [comment]
> You can reproduce it by downloading the repo and following steps described above.
> Its a default nuxt setup

I'll check it out next week! 
I'm taking a flight in a few hours and won't come back until Monday night.

**Comment by alexguevara** [comment]
Great! Thank you.

**Comment by alexguevara** [comment]
Hey Alvaro, did you have a chance to look at the bug?
I`ve tried to debug the issue and it looks like the SSR is the problem.
We can wrap "fullpage" in "no-ssr" tag and everything works fine, however 
its not a solution because we loose SEO.

I`ve bought a pack of fullpage libs and extensions and was planning to use them in the next projects - but I can`t go live with the current one because of this issue.

Could you please help on this?
PS the behaviour is the same with custom nuxt plugin and with the original one. I`ve asked in the nuxt plugin`s repo [(Link)-](https://github.com/vaso2/nuxt-fullpage.js/issues/1) but no luck.

**Comment by alexguevara** [comment]
@alvarotrigo Did you have a chance to look at the issue?
It looks like vue-fullpage is not working with Nuxt SSR setup. 
We can wrap "fullpage" in "no-ssr" tag and everything works fine, however
its not a solution because we loose SEO.
I can`t go live because of this. 
Maybe we could use the fullpage.js version with Nuxt but not the vue-fullpage?
Anyway, I don`t know how...

**Comment by alvarotrigo** [comment]
@alexguevara I didn't have a chance to take a look at it yet.

**Comment by pelkinn** [comment]
hi @alvarotrigo, another month has passed, please read the problem? :(

**Comment by roszpun** [comment]
I've got similar issue. Local development version works as expected. However on production server the plugin does not work as expected.

**Comment by alvarotrigo** [comment]
> hi @alvarotrigo, another month has passed, please read the problem :(

I've read the problem as the rest of you guys :)
However, we haven't come up with a solution so far. 

Good thing is, this whole project is open sourced, so you guys can also try to find a solution, make a pull request and get the issue solved. Let's see if anyone come up with an idea!

**Comment by alvarotrigo** [comment]
We can probably implement the same solution than in [React-fullpage](https://github.com/alvarotrigo/react-fullpage/):
See this file where it says `// NOTE: SSR support`:
https://github.com/alvarotrigo/react-fullpage/blob/master/components/index.js

**Comment by w405287435** [comment]
Is the problem solved？？？    How？

**Comment by alvarotrigo** [comment]
@w405287435 see this pull request:
https://github.com/alvarotrigo/vue-fullpage.js/pull/161

We'll be merging that for the next release, but you can use it so far :)

**Comment by w405287435** [comment]
@alvarotrigo 
Thank u very much!   
I'll try

**Comment by Yanisslsl** [comment]
Maybe try to use the Node environnement variable set to production.
`dev: process.env.NODE_ENV !== 'production'`
