### ISSUE TITLE
Module in package.json leads to none existant file

### ISSUE THREAD

**Issue by dobromir-hristov** [alvarotrigo/vue-fullpage.js#139]
### Description

The `module` field in `package.json` leads to `dist/vue-fullpage.esm.js`, but we have no such file rendered. @alvarotrigo can you check the build commands?

**Comment by alvarotrigo** [comment]
Yeap! Thanks for reporting it!
Want to provide the PR for it?

**Comment by dobromir-hristov** [comment]
Webpack does not build ESM modules. Overall I would not use webpack for bundling, I would go with a Rollup base solution.

**Comment by alvarotrigo** [comment]
> Overall I would not use webpack for bundling, I would go with a Rollup base solution.

Any reason why?

**Comment by dobromir-hristov** [comment]
Configuration can be simpler in most cases. Webpack's bundles are generally larger, and lack ESM support. 

I think both support tree shaking and dead code elimination, which we dont rely on here. 
I guess we dont even need webpack, a simple babel transform may work, never tried it though.

**Comment by dobromir-hristov** [comment]
@alvarotrigo lets just drop that property?

**Comment by alvarotrigo** [comment]
Yeah that's fine, as long as none needs it :)

**Comment by alvarotrigo** [comment]
Fixed on dev.

**Comment by alvarotrigo** [comment]
Merged in the latest version.
