### ISSUE TITLE
Doing something wrong...

### ISSUE THREAD

**Issue by andrewwindfall** [alvarotrigo/vue-fullpage.js#14]
I am trying to call the silentMoveTo function after the OnLeave event trigger but it is creating an endless loop. Any advice would be welcome.

```vue
<full-page :options="options" @after-load="afterLoad" @on-leave="checkPage" id="fullpage">
```

The method is meant to check the pages 'current' variable (passed elsewhere) and if it equals 1, silently move from page1 to page2.

```
Methods:{
checkPage(){
          if(this.current == 1){
      			$.fn.fullpage.silentMoveTo('page1', 'page2');
      	   }
        },
}
```

I am able to alert() as intended when replacing the silentMoveTo() function with alert(). The endless loop occurs when I reference silentMoveTo()

**Comment by alvarotrigo** [comment]
You'd better open this issue on the [fullPage.js repository](https://github.com/alvarotrigo/fullPage.js) as it has nothing to do with the vue component.
