### ISSUE TITLE
location bar not disappearing on mobile phone

### ISSUE THREAD

**Issue by mmommo** [alvarotrigo/vue-fullpage.js#142]
Is there a way to hide the location bar when scrolling down on mobiles like a normal site? Or scrolling like a normal site and adjust when scrolling stops just like the scrollBar option turned on on PCs?

**Comment by alvarotrigo** [comment]
Try using the fullpage.js option `scrollBar:true`.
We developers  have no control over that bar, so the most you can do is turn on the scrollbar so fullPage.js acts as a normal site.
