### ISSUE TITLE
dragAndMove is allowed for vue?

### ISSUE THREAD

**Issue by AKUmajinn** [alvarotrigo/vue-fullpage.js#143]
I try to use this property in my project with setting dragAndMove: true, but it doesn't work.

**Comment by alvarotrigo** [comment]
Did you purchase the Drag And Move extension from the [fullpage.js extensions](https://alvarotrigo.com/fullPage/extensions/) page?

**Comment by AKUmajinn** [comment]
ohh, i understand, I thought the fullpage license was included, thanks for the info

**Comment by alvarotrigo** [comment]
No problem! ;)
