### ISSUE TITLE
How to adapt mobile devices？

### ISSUE THREAD

**Issue by GanZhiXiong** [alvarotrigo/vue-fullpage.js#144]
I ran wepack under demos, which I opened with a browser on my phone to display the following figure. The font size in the red box was too small, so I had to write my own code to control whether it was appropriate or not
![image](https://user-images.githubusercontent.com/27394631/69032403-54b69980-0a17-11ea-81a4-f57dece04420.png)

But you give an example of site on a mobile phone display is very good, should be made fit, I don't have much front development experience,   **so can you tell me your sample web site (https://alvarotrigo.com/vue-fullpage/) is how to carry on the adaptation on mobile devices?**
![image](https://user-images.githubusercontent.com/27394631/69032535-aeb75f00-0a17-11ea-8f21-d5d0b14c13ba.png)

**Comment by alvarotrigo** [comment]
Probably due to the html meta tag:

```html
<meta name="viewport" content="width=device-width,initial-scale=1">
 ``` 

Which is present on the vue-fullpage site and not on the example.
