### ISSUE TITLE
prerender-spa-plugin causes Fullpage multiple initialization

### ISSUE THREAD

**Issue by rastapezzolo** [alvarotrigo/vue-fullpage.js#145]
I used prerender-spa-plugin to pre render vue application. This causes Fullpage to rise an exception because of too many initialization.

I use Laravel + Vue.js and the vue-fullpage component, I used an index.html  file to prerender the vue app in with html-webpack-plugin and prerender-spa-plugin. (following this article https://vuejsdevelopers.com/2017/04/01/vue-js-prerendering-node-laravel/)
The whole app works like a charm, except for vue-fullpage causing 

fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!

Is there any way to prevent this? Thank you in advance

Laravel 6.0
Vue ^2.6.10
vue-fullpage ^0.1.4

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by wohuitizuqiu** [comment]
Another way to ask, what can I do to make Fullpage non-global initialization? (Addition: the prerender-spa-plugin plugin will pre-render into multiple static pages according to the route set when the project is built, resulting in Fullpage being initialized multiple times.)

**Comment by alvarotrigo** [comment]
I still not sure to understand what's the issue behind it.
I'll wait for an isolated reproduction to clarify that :)

**Comment by n-martynova** [comment]
@rastapezzolo @wohuitizuqiu 
Fixed it this way.

`mounted() {
        let refs = this.$refs
        window.onload = function() {

            let fullpageEnabled = document.documentElement.classList.contains('fp-enabled')

            if (!fullpageEnabled) {
                refs.fullpage.init()
            } else {
                document.documentElement.classList.remove('fp-enabled')
                refs.fullpage.destroy('all')
                refs.fullpage.init()
            }
        }
    },`

**Comment by alvarotrigo** [comment]
@rastapezzolo  Any reproduction please? We would like to look into this issue and fix it if possible.
