### ISSUE TITLE
plugin not working: 

### ISSUE THREAD

**Issue by kristijan97** [alvarotrigo/vue-fullpage.js#146]
**Errors**: https://imgur.com/lnaD6fO

**Steps:**
> npm add vue-fullpage.js

```
import VueFullPage from 'vue-fullpage.js'
import App from './App.vue'
Vue.use(VueFullPage)
```

```<full-page ref="fullpage" id="fullpage" licenseKey="asdasdasd" :options="fullpageOptions">```

> fullpageOptions: {
>       licenseKey: 'YOUR_KEY_HERE'
> }

What's the problem?
See error:
<FullPage> at /Users/alvarotrigolopez/Sites/vue-fullpage.js/src/FullPage.vue

**Comment by dobromir-hristov** [comment]
Hi there, we are pretty sure it works, so there is a problem with your configuration.
Please take a second look at the examples and your code.
Maybe share your code in a codepen or something?

**Comment by alvarotrigo** [comment]
You can see it working as expected on this codepen:
https://codepen.io/alvarotrigo/pen/zpQmwq

**Comment by kristijan97** [comment]
I tried an example from git, but inside you are importing fullpage.js from dist which is already built, my bad, sorry

**Comment by alvarotrigo** [comment]
No problem! Glad you got it working now!

If you believe we should clarify the docs somehow, please let us know and we'll do our best to improve them!

**Comment by kristijan97** [comment]
Well, I believe that we can improve
https://github.com/alvarotrigo/vue-fullpage.js/blob/master/demos/webpack/src/main.js
`import VueFullPage from '../../../dist/vue-fullpage.js'`
This is webpack example. You should replace this path with 'vue-fullpage.js'
The file from dist folder is already built for you machine and it is not working anywhere else

**Comment by alvarotrigo** [comment]
Yeah the reason its like that is so I can test the new version before publishing it to npm :)
