### ISSUE TITLE
fullPage used in more than one component give "multiple initialized" error

### ISSUE THREAD

**Issue by sebastianluszczek** [alvarotrigo/vue-fullpage.js#148]
I try to use vue-fullPage in app in multiple place. I use initialization one in _main.js_. When opening first route where fullPage is, everything is ok, but after redirecting ($router.push()) to another route with _fullPage.js_ component i got

"Fullpage.js can only be initialized once and you are doing it multiple times!"

Is it possible to use it in multiple routes (components)?

**Comment by dobromir-hristov** [comment]
Yeah. Please provide us with a reproducible example, where we can test whats wrong. I have not had this problem before, nor has anyone complained as well.

**Comment by sebastianluszczek** [comment]
Thanks for reply. I had problem with some production code, and after building something simple and similar to reproduce error I find problem.
My Router uses _keep-alive_, after removing this tag everything work excellent!
