### ISSUE TITLE
<v-footer> does not appear when using fullpage comp

### ISSUE THREAD

**Issue by dannascimento** [alvarotrigo/vue-fullpage.js#15]
Hi there!

Trying to setup a footer into the last fullpage's section, although the footer isn't rendered at all. Even if we check at the DOM we can't find the code in place.

Is there some kind of restriction to combine both? Any tweaks to make it work?

Cheers.
Dan

**Comment by dannascimento** [comment]
Just figure out by myself. Fullpage.js does not support this. As an alternative, you can use https://alvarotrigo.com/fullPage/examples/oneSection.html

**Comment by alvarotrigo** [comment]
Why not making use of an auto height section for the footer?
See [this example](https://alvarotrigo.com/fullPage/examples/autoHeight.html).
