### ISSUE TITLE
vue-fullpage.js + extensions

### ISSUE THREAD

**Issue by spyderdsn** [alvarotrigo/vue-fullpage.js#150]
Hi, I just purchased an extension Scroll Horizontally and noticed your documentation is not very clear what next.

https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension

Here you say replace whole main file fullpage.min.js with fullpage.extensions.min.js. But this is impossible in VUE.

Here: https://github.com/alvarotrigo/vue-fullpage.js/blob/master/README.md

```
import Vue from 'vue'
import 'fullpage.js/vendors/scrolloverflow' // Optional. When using scrollOverflow:true
import './fullpage.scrollHorizontally.min' // Optional. When using fullpage extensions
import VueFullPage from 'vue-fullpage.js'
```

but "fullpage.scrollHorizontally.min" nowhere to be found?

Thanks

**Comment by alvarotrigo** [comment]
> Here you say replace whole main file fullpage.min.js with fullpage.extensions.min.js. But this is impossible in VUE.

No problem! :)
On the purchase of the extension you got the extension files and with them a file named "How to use it.html" in which it redirects you to the documentation for the vue-fullpage component:

![image](https://user-images.githubusercontent.com/1706326/69748602-02792500-1149-11ea-8d25-80b976c48303.png)

Basically you  don't have to replace that file and you basically have to follow the instructions in the [vue-fullapge.js docs](https://github.com/alvarotrigo/vue-fullpage.js#usage).
There you'll find references to how to import extensions.

**Comment by spyderdsn** [comment]
<img width="340" alt="Screen Shot 2019-11-29 at 8 15 03 pm" src="https://user-images.githubusercontent.com/7193691/69857949-19547e80-12e5-11ea-840f-0e6769fb68f8.png">
<img width="401" alt="Screen Shot 2019-11-29 at 8 15 11 pm" src="https://user-images.githubusercontent.com/7193691/69857950-19547e80-12e5-11ea-8994-8701019bc9ce.png">
<img width="392" alt="Screen Shot 2019-11-29 at 8 15 25 pm" src="https://user-images.githubusercontent.com/7193691/69857952-19547e80-12e5-11ea-8654-9a23323b905e.png">

I don't have `fullpage.scrollHorizontally.min` in any of the modules?  I'm also struggling to find a structure of the horizontal sections. How to nest them correctly...?

Thanks

**Comment by spyderdsn** [comment]
scrolloverflow & vue-fullpage.js works correctly.

**Comment by alvarotrigo** [comment]
> I don't have `fullpage.scrollHorizontally.min` in any of the modules?

When you purchase it through the [fullpage.js extensions](https://alvarotrigo.com/fullPage/extensions/) page you get a link to download it in the purchase confirmation email. It is a green button on the email saying something like "Download".

**Comment by spyderdsn** [comment]
I did just didn't realise there are some files under the purchase page...I've got it working now. BDW it will be good to have doted nav for the horizontal slides too. Thanks

**Comment by alvarotrigo** [comment]
> BDW it will be good to have doted nav for the horizontal slides too.

You do have it :)
See the option `slidesNavigation` and demos like this:
https://alvarotrigo.com/fullPage/examples/navigationH.html

**Comment by jeffreykthomas** [comment]
Hello. Has the process for installing scrolloverflow changed? I don't see in the vue-fullpage docs what the process is for importing the scolloverflow.js file. Above it appears they have installed the full package fullpage.js, in addition to vue-fullpage.js, in order to be able to import scrolloverflow, is that correct?

**Comment by alvarotrigo** [comment]
> Hello. Has the process for installing scrolloverflow changed?

Yes, the file is no longer required. You can read more about it on the migration guide from v3 to v4:
https://github.com/alvarotrigo/fullPage.js/wiki/Migration-from-fullPage-v3-to-fullPage-v4#6-scrolloverflow-option-wont-require-an-external-file

**Comment by jeffreykthomas** [comment]
Okay thank you. Was struggling to get it to work because I had parallax set to true... turning that off did the trick
