### ISSUE TITLE
Scrolling "jitters" on iOS after returning to page. 

### ISSUE THREAD

**Issue by kdesimini** [alvarotrigo/vue-fullpage.js#152]
### Description
When viewing a page for the first time, everything scrolls correctly. After suspending the browser(chrome or safari on mobile) and re-opening, the scrolling appears to "jitter" and animations are not smooth, but rather extremely fast. 

[Video of the issue - youtube](https://youtu.be/XRle5B2DK1o)
### Link to isolated reproduction with no external CSS / JS
[Ideally in codepen.io or codesandbox.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]
The main example page does this. 
[https://alvarotrigo.com/vue-fullpage/](https://alvarotrigo.com/vue-fullpage/)

(A personal site but will occur every single time the steps below are performed)
[https://www.beautifulinspirationsllc.com/](https://www.beautifulinspirationsllc.com/)
### Steps to reproduce it
1. Open Safari or Chrome on iOS. 
2. Navigate to the webpage. 
3. Open a new tab or suspend the app. 
4. Return to the webpage and attempt to scroll.

### Versions 
iOS 12.4
iPhoneXS Max
Safari
Google chrome - 78.0.3904.84

**Comment by alvarotrigo** [comment]
Sounds more like a browser issue / bug than a fullPage.js one :)
I don't think there's much we can do there.

**Comment by kdesimini** [comment]
Ah yes, my mistake. It looks like safari is working fine. How can I report a bug like this to chrome for iOS? It must have something to do with suspending the application and iOS WKWebView

**Comment by alvarotrigo** [comment]
You can take a look at this:
https://webkit.org/reporting-bugs/

But they will probably ask you to create an isolated reproduction, so you'll have to extract the relevant  code and create a small reproduction with it. 

Probably an issue with animating the translade3d property of CSS.

**Comment by kdesimini** [comment]
Your main website works so well on chrome though. Would getting the drag and move extension *maybe* solve the issue? Or would it just be best to not use a wrapper? Thanks for the help though, I’ll take a look into that!

**Comment by alvarotrigo** [comment]
> Would getting the drag and move extension _maybe_ solve the issue?

Seems like that could be a solution as per your comments.
Feel free to purchase it and try it. Make sure you do not generate any activation key  and you'll be able to get a full refund for 30 days.

The drag and move extension doesn't animate sections with CSS and seems like those kind of animations could be the cause of the initial bug.

**Comment by kdesimini** [comment]
It seems chrome just isn't friendly haha. Thanks for the help!

**Comment by alvarotrigo** [comment]
Glad you managed to solve it!
