### ISSUE TITLE
How to keep fullpage running while leaving the page on Vue?

### ISSUE THREAD

**Issue by krisons** [alvarotrigo/vue-fullpage.js#153]
I am getting strange effect when I am navigate to route using fade transition. 

At the moment when I navigate to a route the fullpage.js loses the height of its sections and I see a stuck slider while page fades out. Is there a way to keep height of these sections? 

Nuxt.js 2.10.2
fullpage.js 3.0.7

**Comment by dobromir-hristov** [comment]
Sounds more like a CSS issue to me.

**Comment by krisons** [comment]
@dobromir-hristov no, I can clearly see that before navigate my fullpage sections look like this:

`<section data-v-7f245110="" data-anchor="dining" class="section is-paddingless fp-section fp-table" data-fp-styles="null" style="height: 964px;"></section>`

and immediately after I click on the router link it becomes:

`<section data-v-7f245110="" data-anchor="dining" class="section is-paddingless fp-section" data-fp-styles="null" style="null"></section>`

Please note, it also loses class `fp-table`

When sections loses height they immediately becomes smaller and I can see several sections on on the screen. I can record video if needed.

**Comment by krisons** [comment]
Solved!! I am overriding section height by vue! Works a charm!

However, I have noticed that after click fullpage restarts: shows me first slide immediately after router click. Is there a way to say fullpage to do not restart?

**Comment by alvarotrigo** [comment]
Possibly related with issue https://github.com/alvarotrigo/vue-fullpage.js/issues/81

**Comment by alvarotrigo** [comment]
> When sections loses height they immediately becomes smaller and I can see several sections on on the screen. I can record video if needed.

That sounds like its because fullpage.js is being destroyed, when perhaps, it shouldn't ?

Can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
