### ISSUE TITLE
Toggling Autoscroll

### ISSUE THREAD

**Issue by versionmj** [alvarotrigo/vue-fullpage.js#154]
Hello,

I am having an issue toggling autoScrolling in response to events.  The pen below reproduces the issue.  Dynamically calling `$refs.fullpage.api.setAutoScrolling(false)` turns autoScrolling functionality off but then calling `$refs.fullpage.api.setAutoScrolling(true)` is hit or miss.  i.e. autoScrolling sometimes works immediately and other times requires some other action (resizing the page or navigating via anchors) before it works.

https://codepen.io/dresscode/full/MWYodYv

### Steps to reproduce it
1. Click 'AutoScroll Off' button and check scrolling functionality
2. Click 'AutoScroll On' button and check scrolling functionality again
3. Repeat

**Comment by alvarotrigo** [comment]
I can't seem to reproduce the issue.
What browser and  device are you using?

**Comment by versionmj** [comment]
Device: MacBook Pro
Browsers: 
   Chrome v.79.0.3945.88, 
   Firefox Developer's Edition v.72.0b10
   Safari v.13.0.4

**Comment by dobromir-hristov** [comment]
For me it worked. the times it didnt, I had to focus in the browser.

**Comment by versionmj** [comment]
@dobromir-hristov 

What do you mean "focus in the browser"?

**Comment by dobromir-hristov** [comment]
Click tab or click inside the window :)

**Comment by versionmj** [comment]
@dobromir-hristov Something is off here.  Just prior to responding with my device and browsers, I tried that pen again in all three of those browsers and the issue remained.  Now, I am trying again, after reading your response, and it works. It does not, however, work in my app.

**Comment by versionmj** [comment]
> For me it worked. the times it didnt, I had to focus in the browser.

Could you please explain "the times it didn't".

**Comment by alvarotrigo** [comment]
> Could you please explain "the times it didn't".

I assume he means the codepen iframe with the resulting page was not focused.

I'll close this issue as I can't seem to reproduce any issue with it.
If you still can reproduce it please let us know how can we do it, on which browser, version and device.

And if you have a video, that'd be great too :)
