### ISSUE TITLE
a tag is blocked by fullpage element

### ISSUE THREAD

**Issue by navabase** [alvarotrigo/vue-fullpage.js#155]
### We cannot use the a tag on our Webpage.
We are using Vue.js and the vue plugin vue-fullpage.js. We have 3 sections and one nav at the top of the page. We cannot click those links, because there are hidden under the fullPage element. We tried to add a z-index to bring it to the front, but it did not work. After adding the nav element into the fullPage element, we could use the a tags, but this did not solve our problem, because we want to fix the position of the nav element on the top of the page. 
```
 <header>
        <nav>
            <a href="#">Contact</a> 
        </nav>
 </header>
 <full-page>
   ....Content
 </full-page>

```
How can we use a tags on top of the fullPage element?
thanks in advanced.

**Comment by navabase** [comment]
Here´s the pen: https://codepen.io/johann_su/pen/JjovzNN

Thanks for the help in advance.

**Comment by alvarotrigo** [comment]
That's a css issue, just add this:
```css
nav{
    position:fixed;
    z-index:99;
}
```
