### ISSUE TITLE
Init render incorrect on specific anchor

### ISSUE THREAD

**Issue by ThomCM** [alvarotrigo/vue-fullpage.js#157]
Hi,

I've got a website https://bornsocial.co.uk which works very well for the most part but when accessing the site via one specific anchor (https://bornsocial.co.uk/#white-papers) there's an issue with the initial render resulting in it being cut-off. The moment you navigate away from the section it corrects. I understand I'm not providing an isolated reproduction but I was wondering whether there are any common pitfalls that I might have fallen victim too? It's worth noting that the layout is almost identical to the _posts_ anchor above.

On a separate note, I'm having to setAllowScrolling(false) and micro-manage user position whilst they're engaged with the contact form on mobile. Again I was wondering if there were any best practices WRT input fields and touch devices as this isn't particularly elegant.

I'm using vue-fullpage and have a commercial developers license.

TIA

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/), [codepen](https://codepen.io/alvarotrigo/pen/qqabrp) (or your own isolated page), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by ThomCM** [comment]
I was wondering about best practices when incorporating contact forms into fullpage.js sections.

& common pitfalls that may cause an init render for a specific anchor to be incorrect whilst it works fine for all other anchors and corrects itself immediately after leaving that problem section.

**Comment by alvarotrigo** [comment]
Adding an isolated link to your specific issues will help you to get a more precise answer :)
