### ISSUE TITLE
Not working on IE 11 or lower

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/vue-fullpage.js#16]
Only works in Edge.

**Comment by eastwook80** [comment]
I tested using webpack-simple template
in my case working on IE11

1. full code copy from https://codepen.io/alvarotrigo/pen/zpQmwq 

2. referrenced [solution](https://github.com/alvarotrigo/vue-fullpage.js/issues/4#issuecomment-366520470)
installed two libraries

3. remove one line in webpack.conf.js
{
test: /.js$/,
loader: 'babel-loader',
exclude: /node_modules/ --> remove
}

4. install 'babel-polyfill'

5. set polyfill in main.js at first line
import 'babel-polyfill'

**Comment by alvarotrigo** [comment]
The stand-alone demo works now on IE 11 on the latest release 0.0.2
