### ISSUE TITLE
"fixedElements" have problems with HMR.

### ISSUE THREAD

**Issue by JeHwanYoo** [alvarotrigo/vue-fullpage.js#162]
### Description
<img src="https://i.ibb.co/ssDKpfR/2020-03-16-5-47-29.png" alt="2020-03-16-5-47-29" border="0">

I was told that fixedElements exports elements out from fullpage.js.
So it seems that the problem is caused by HMR. 
It does not erase existing elements.
I am experimenting with a fullpage in a project made with vue-cli.

### Versions 
Brave Browser 1.4.96
MacOS Catalina 10.15.4 Beta
fullpage.js 3.0.8
vue-fullpage.js 0.1.5

**Comment by JeHwanYoo** [comment]
I am temporarily using the code below to solve it.

(typescript)
```typescript
// when mounted
mounted() {
  const elems = document.getElementsByClassName('fixed-elements');
  if (elems.length > 1) {
    // remove previous rendering
    for (let i = 0; i < elems.length - 1; i++) {
      const el = elems.item(i);
      el?.parentNode?.removeChild(el);
    }
 }
}
```

**Comment by alvarotrigo** [comment]
I guess we can close this by now?
Somehow I missed this issue.

What is HMR btw?

Can you try again now with the latest version of the vue wrapper?
I'll close the issue, but feel free to open it again.
