### ISSUE TITLE
URL -->  abc.com/firstPage/slide1 instead of abc.com/pagexyz#firstPage/1

### ISSUE THREAD

**Issue by jochenthomas** [alvarotrigo/vue-fullpage.js#164]
Hi,
I am wondering if it would be possible to change the URL to a simple "speaking" URL.
Would this be possible using vue-router (nuxt)?

**Example:**
abc.com/fruits/
abc.com/fruits/apples
abc.com/fruits/cherry
abc.com/meat/
abc.com/meat/cow

I would like to avoid to work with "index.htm#fruits/1", each slide shall have its own name...
Fruits or meat would be the section and apples/cherry would be the slides.

Thanks for some directions or maybe a small code example...

**Comment by alvarotrigo** [comment]
Nope. We are still working on it on fullpage.js,  here's a pull request:
https://github.com/alvarotrigo/fullPage.js/pulls

**Comment by jochenthomas** [comment]
Thanks for fast answer :-)
