### ISSUE TITLE
Can't hide fixed elements in a specific section and can't create a menu that recognizes the active slides

### ISSUE THREAD

**Issue by peter2606** [alvarotrigo/vue-fullpage.js#166]
I'm trying to hide my bnav and the menus only on the first section, also the SlidesMenu is not working since it's only recognizing the active sections.

That's the link of what i did and if you scroll through slides you can see that the SlidesMenu is not working. I assume it is related to the anchors, but so far i did not understand if it's possible to create data-menuanchors for the slides.
https://codesandbox.io/s/loving-sammet-c7lgb?file=/src/components/FullPage.vue

### Steps to reproduce it
1. [Scroll to the second section]
2. [Scroll through slides]

### Versions 
[Google Chrome, Mac]

**Comment by alvarotrigo** [comment]
You have two options:

1 - You can use [fullpage.js state classes to use CSS conditions.](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs. 

2- You can use [fullPage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) to trigger your code on different states of your site.

I hope that helps you here :)

**Comment by peter2606** [comment]
Thank you so much! i figured out how to do both the things thanks to the
video you did time ago.
Congratulations for your framework! it is awesome :D

Il giorno dom 3 mag 2020 alle ore 18:11 Álvaro <notifications@github.com>
ha scritto:

**Comment by alvarotrigo** [comment]
Thanks!! :)
Glad you managed to make it work!
