### ISSUE TITLE
It comes back to the top after a while

### ISSUE THREAD

**Issue by wphubs** [alvarotrigo/vue-fullpage.js#170]
Hello， Mobile page exceeds screen size，about a few seconds，back to top.

How to cancel back to the top？

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by wanxe** [comment]
I'm having exactly this issue but for desktop sizes. And it can't let me go back to the 1st slide. (Nuxt project with ClientOnly)

There's the config:
`      fullPageOptions: {
        licenseKey: 'XXXX',
        scrollBar: true,
        controlArrows: false,
        loopBottom: false
      },`

**Comment by alvarotrigo** [comment]
@wanxe can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
I'll close the issue until an isolated reproduction is provided.
