### ISSUE TITLE
Callback Index Inaccurate to Section #

### ISSUE THREAD

**Issue by jamespurnama1** [alvarotrigo/vue-fullpage.js#173]
### Description
Did a simple test of the callback. The index is inaccurate, meaning index 0 is not always section 1, index 1 is not always section 2, and so on. On several occasions, multiple sections can have the same index.

### Steps to reproduce it
1. Create a Vue app
2. Install and import vue-fullpage.js
3. Create a 3 section fullpage
```html
<template>
  <div id="app">
    <full-page ref="fullpage" :options="options" @after-load='afterLoad' id='fullpage'>
      <div class="section">
      </div>
      <div class="section">
      </div>
      <div class="section">
      </div>
    </full-page>
  </div>
</template>
```
4. List callback in options
`afterLoad: this.afterLoad`
5. Write the callback simple test
```javascript
    afterLoad(destination) {
      if (destination.index === 0) {
        console.log('going to section 1');
      }
      if (destination.index === 1) {
        console.log('going to section 2');
      }
      if (destination.index === 2) {
        console.log('going to section 3');
      }
    }
```

### Versions 

- Chrome 84.0.4147.89
- Safari 13.1.2 (15609.3.5.1.3)
- Firefox 78.0.2

Running on macOS Catalina 10.15.6

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/)?

**Comment by jamespurnama1** [comment]
Here's the [codepen link](https://codepen.io/jamespurnama1/pen/LYGaVmO)
You can check console while scrolling.

**Comment by alvarotrigo** [comment]
The afterLoad param is wrong.
First one is always `origin` as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)

```js
	afterLoad: function(origin, destination, direction){},
``` 

I hope that explains those results :)

**Comment by jamespurnama1** [comment]
ah I see, turns out my linter is forcing me to remove origin & direction param since it's not used inside the function {}.
For anyone in the future who stumbles at the same problem simply ignore the linter.

```javascript
methods: {
    afterLoad(origin, destination, direction) { // eslint-disable-line
    }
```

Thanks & sorry for the trouble.

**Comment by alvarotrigo** [comment]
No worries! I'm glad you figure out a good solution for it!
