### ISSUE TITLE
[Question] Slide overflowing to next section

### ISSUE THREAD

**Issue by jamespurnama1** [alvarotrigo/vue-fullpage.js#178]
### Description
In the codesandbox, the slide is overflowing to the next section & not horizontally, am I doing something wrong?

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/s/fullpagejs-20j19

**Comment by alvarotrigo** [comment]
You might be missing the css file?
See the demo here and compare with yours:
https://codepen.io/alvarotrigo/pen/zpQmwq

Also a webpack one here:
https://github.com/alvarotrigo/vue-fullpage.js/tree/master/demos/webpack
