### ISSUE TITLE
如何动态创建slide在section中

### ISSUE THREAD

**Issue by zhaoxiaozhao1** [alvarotrigo/vue-fullpage.js#179]
### Link to isolated reproduction with no external CSS / JS
[Ideally in codepen.io or codesandbox.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Here's the answer:
https://github.com/alvarotrigo/vue-fullpage.js#dynamic-changes

**Comment by zhaoxiaozhao1** [comment]
如何在动态创建的slide中 插入自定义的组件。和苦恼，麻烦回复一下，谢谢啦

**Comment by alvarotrigo** [comment]
Google translator is not great  unfortunately :)

English please?

**Comment by zhaoxiaozhao1** [comment]
Be solved，thank you
