### ISSUE TITLE
Dynamically generated sections

### ISSUE THREAD

**Issue by dsheyp** [alvarotrigo/vue-fullpage.js#18]
Hi

Thanks for the cool component!

I'd like to add a varying number of sections dynamically during compile time, but I get an error saying, that fullpage can only be initialized once. How would it be possible to achieve what I'm trying to?
```

<template>
  <div>
      <full-page :options="options" v-for="s in sections" :key="s.Index">
        <full-page-section :section="s" />
      </full-page>
  </div>
</template>
```

Many thanks for any ideas
dsheyp

**Comment by dsheyp** [comment]
I think I got it how it works:
```

<template>
  <span>
      <full-page :options="options">
        <template v-for="s in sections">
          <full-page-section :section="s" />
        </template>
      </full-page>
  </span>
</template>
```

**Comment by alvarotrigo** [comment]
Just take a look at [the codepen provided in the docs](https://codepen.io/alvarotrigo/pen/zpQmwq).

```javascript
methods: {
        addSection: function(e) {
          e.preventDefault();
          var newSectionNumber = $('.fp-section').length + 1;

          //adding section
          $('#fullpage').append(`<div class="section"><h3>Section ${newSectionNumber}</h3></div>`);

          //adding anchor for the section
          this.options.anchors.push(`page${newSectionNumber}`);

          //we have to call `update` manually as DOM changes won't fire updates
          //requires the use of the attribute ref="fullpage" on the
          //component element, in this case, <full-page>
          this.$refs.fullpage.update();
        },
```

**Comment by dsheyp** [comment]
hi alvaro

many thanks for the codePen example, i'm sure it will be very helpful in some place for me.

however, it might not be the answer for my original question. what i meant was server side generation of sections with nuxt.js - but everything is working now with the template from my second post.

thanks
dsheyp

**Comment by alvarotrigo** [comment]
> what i meant was server side generation of sections with nuxt.js

Not something that belongs here. This is a front-end component for vue.js. 
Any backend you do is not a matter of vue-fullpage.js.

**Comment by dsheyp** [comment]
ok, i understand. nuxt.js is vue.js - for the server - therefore out of scope of vue-fullpage.js. but it does also work in nuxt.js. that's cool.

thx
