### ISSUE TITLE
Can't pinch to zoom on phone

### ISSUE THREAD

**Issue by rawnanoob** [alvarotrigo/vue-fullpage.js#180]
### Link to isolated reproduction with no external CSS / JS
[Ideally in codepen.io or codesandbox.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]
any mobile browser

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
That's a well known issue and there's [an open issue about it](https://github.com/alvarotrigo/fullPage.js/issues/1268) on the main fullPage.js repository.

I'll close this one to have it all centralised in one place.

Short answer:
There's now ay to pinch and zoom yet unless you use the option `autoScrolling:false` to turn off snap scroll.
No intention of implementing this in the short term. Reason being that responsive sites rarely require users to pinch and zoom.
