### ISSUE TITLE
Safari page markers are not formatted correctly

### ISSUE THREAD

**Issue by jclaessens97** [alvarotrigo/vue-fullpage.js#182]
### Description
On safari the "page markers" on the right side are not formatted correctly.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/10177148/104810657-7582a680-57f6-11eb-95ed-f72fa3d5d62b.png">

### Versions 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/10177148/104810676-88957680-57f6-11eb-9654-3de191f2cd39.png">

**EDIT** apparently already reported in #165

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Issue fixed!
https://alvarotrigo.com/vue-fullpage/#page1
