### ISSUE TITLE
vue 3 support

### ISSUE THREAD

**Issue by aminparsa18** [alvarotrigo/vue-fullpage.js#183]
works completely fine on vue 2.6
but im getting following error using vue 3

"TypeError: window.Vue.use is not a function"
is it supported?

**Comment by dobromir-hristov** [comment]
It is not ported for Vue 3 yet.

**Comment by alvarotrigo** [comment]
Apparently [they still don't have a guide](https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes) for porting to version 3 and they recommend to wait for it.
![image](https://user-images.githubusercontent.com/1706326/107122149-30eaa800-6896-11eb-85fc-f89d2dbbac8c.png)

**Comment by zhengyanxiong** [comment]
Hope to support Vue3.0 as soon as possible 库😭😭😭😭😭

**Comment by alvarotrigo** [comment]
@zhengyanxiong want to provide a pull request?
I'm open to them :)

I haven't tried v3 yet.

**Comment by zhengyanxiong** [comment]
@alvarotrigo  I am trying to use vue3, but I keep getting the following error and I don't know how to solve it.
```
Uncaught TypeError: Cannot read property '_c' of undefined
    at Proxy.render (vue-fullpage.js:424)
    at renderComponentRoot (runtime-core.esm-bundler.js:846)
    at componentEffect (runtime-core.esm-bundler.js:4280)
    at reactiveEffect (reactivity.esm-bundler.js:42)
    at effect (reactivity.esm-bundler.js:17)
    at setupRenderEffect (runtime-core.esm-bundler.js:4263)
    at mountComponent (runtime-core.esm-bundler.js:4222)
    at processComponent (runtime-core.esm-bundler.js:4182)
    at patch (runtime-core.esm-bundler.js:3791)
    at componentEffect (runtime-core.esm-bundler.js:4298)
```

**Comment by FJLendinez** [comment]
As a temporal solution you can copypaste this component into your source code.
```
<template>
  <div ref="fullpage">
    <slot></slot>
  </div>
</template>

<script>
import fullpage from "fullpage.js/dist/fullpage.extensions.min";

export const EVENTS = [
  "afterLoad",
  "onLeave",
  "afterRender",
  "afterResize",
  "afterResponsive",
  "afterSlideLoad",
  "onSlideLeave",
];

export const METHODS = [
  "moveSectionUp",
  "moveSectionDown",
  "moveTo",
  "silentMoveTo",
  "moveSlideRight",
  "moveSlideLeft",
  "setAutoScrolling",
  "setFitToSection",
  "fitToSection",
  "setLockAnchors",
  "setAllowScrolling",
  "setKeyboardScrolling",
  "setRecordHistory",
  "setScrollingSpeed",
  "destroy",
  "reBuild",
  "setResponsive",
  "responsiveSlidesToSections",
  "responsiveSlidesToSlides",
];
function camelToKebab(string) {
  return string.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}
export default {
  methods: {
    build() {
      var slideSelector = this.options.slideSelector || ".slide";
      var sectionSelector = this.options.sectionSelector || ".section";
      const activeSectionIndex = fp_utils.index(
        document.querySelector(sectionSelector + ".active")
      );
      const activeSlide = document.querySelector(
        sectionSelector + ".active " + slideSelector + ".active"
      );
      const activeSlideIndex = activeSlide ? fp_utils.index(activeSlide) : -1;
      this.unmount();
      if (activeSectionIndex > -1) {
        fp_utils.addClass(
          document.querySelectorAll(sectionSelector)[activeSectionIndex],
          "active"
        );
      }
      if (activeSlideIndex > -1) {
        fp_utils.addClass(activeSlide, "active");
      }
      this.init();
    },
    unmount() {
      if (
        typeof fullpage_api !== "undefined" &&
        typeof fullpage_api.destroy !== "undefined"
      ) {
        fullpage_api.destroy("all");
      }
    },
    emitEvent(name, args) {
      // Emit event on Vue way
      this.$emit(camelToKebab(name), ...args);
      // Run event's handler with non Vue way
      if (this.options.name) {
        this.options[name].apply(this, args);
      }
    },
    init() {
      // eslint-disable-next-line
      this.api = new fullpage(this.$refs.fullpage, this.options);
    },
  },
  mounted() {
    !this.skipInit && this.init();
  },
  beforeUnmount() {
    if (typeof this.api !== "undefined") {
      this.unmount();
    }
  },
  data() {
    return {
      events: EVENTS.reduce((eventsHandlers, event) => {
        return {
          ...eventsHandlers,
          [event]: (...args) => {
            this.emitEvent(event, args);
          },
        };
      }, {}),
      api: undefined,
    };
  },
  props: {
    options: {
      type: Object,
      required: true,
    },
    skipInit: {
      type: Boolean,
      default: false,
    },
  },
  watch: {
    options: {
      deep: true,
      handler() {
        this.build();
      },
    },
  },
};
</script>
```

The main change is to replace the **beforeDestroy** event to **beforeUnmount**

**Comment by xianchaokuan** [comment]
> @alvarotrigo I am trying to use vue3, but I keep getting the following error and I don't know how to solve it.
> 
> ```
> Uncaught TypeError: Cannot read property '_c' of undefined
>     at Proxy.render (vue-fullpage.js:424)
>     at renderComponentRoot (runtime-core.esm-bundler.js:846)
>     at componentEffect (runtime-core.esm-bundler.js:4280)
>     at reactiveEffect (reactivity.esm-bundler.js:42)
>     at effect (reactivity.esm-bundler.js:17)
>     at setupRenderEffect (runtime-core.esm-bundler.js:4263)
>     at mountComponent (runtime-core.esm-bundler.js:4222)
>     at processComponent (runtime-core.esm-bundler.js:4182)
>     at patch (runtime-core.esm-bundler.js:3791)
>     at componentEffect (runtime-core.esm-bundler.js:4298)
> ```

how did u resolve it?

**Comment by ArseniyShestakov** [comment]
Can't make it find jQuery when using in Vue3 project using TypeScript.

**Comment by alvarotrigo** [comment]
> Can't make it find jQuery when using in Vue3 project using TypeScript.

fullpage.js doesn't require jQuery :)

**Comment by ArseniyShestakov** [comment]
@alvarotrigo oops, my bad then.

I just got usual ```Uncaught (in promise) TypeError: $(...) is null``` selector error during my attempts to make it work with Vue 3 + TypeScript and falsely assumed the problem has something to do with jQuery.

**Comment by alvarotrigo** [comment]
As the issue says, it's not ported yet to Vue 3.

**Comment by matthiaswid** [comment]
When will it work with vue 3?

**Comment by alvarotrigo** [comment]
@matthiaswid whenever we can :)
Feel free to provide a pull request if this is something you can provide value to.

**Comment by ypc-git** [comment]
When will it work with vue 3?

**Comment by alvarotrigo** [comment]
@ypc-git whenever we can :)
Feel free to provide a pull request if this is something you can provide value to.

**Comment by sebastianbayer** [comment]
when is a working vue3 version to be expected? this year or more likely next year..? (we would appreciate to use fullpage.js for a project but timing is kind of crucial 😬)

**Comment by alvarotrigo** [comment]
I don't have a date in mind. As soon as fullPage.js 4 gets released I'll start working on this.
Can be around December 2021 or a bit later next year.

**Comment by alvarotrigo** [comment]
But if any of you guys want to contribute to it and do the change, I'll be more than happy to accept your PR :)

**Comment by alvarotrigo** [comment]
Thanks to @JonathanSchndr the latest vue-fullpage.js version supports vue3! (and fullpage.js v4!) 💪
