### ISSUE TITLE
Nuxt.js fullPage: The option `scrollOverflow:true` requires the file `scrolloverflow.min.js`. 

### ISSUE THREAD

**Issue by skuljanze95** [alvarotrigo/vue-fullpage.js#187]
Hello, 

How can I solve this problem in nuxt.js 

fullPage: The option `scrollOverflow:true` requires the file `scrolloverflow.min.js`. Please include it before fullPage.js.

**Comment by alvarotrigo** [comment]
See the usage part here:
https://github.com/alvarotrigo/vue-fullpage.js#usage
