### ISSUE TITLE
NuxtJs TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Anthony2511** [alvarotrigo/vue-fullpage.js#188]
### Description

I used the option **nuxt-fullpage.js** as plugin with command :

`npm install --save nuxt-fullpage.js`

But when I compile my code, everything launches as it should but, I have this error message which appears in the console of the browser

<img width="569" alt="Capture d’écran 2021-03-19 à 14 43 57" src="https://user-images.githubusercontent.com/17065512/111789644-aac47700-88c1-11eb-9927-172fdce5391f.png">

and when i try to scroll, this is what the console gives me as an error message

<img width="587" alt="Capture d’écran 2021-03-19 à 14 50 54" src="https://user-images.githubusercontent.com/17065512/111790819-e6137580-88c2-11eb-8219-43cc53930ba7.png">

I also tried with the component `<no-ssr>`, but result is the same.

My view **index.vue**
```javascript
 <template>
  <div class="container">
    <Header/>
    <client-only>
      <full-page ref="fullpage" :options="options" id="fullpage">
        <section></section>
      </full-page>
    </client-only>
  </div>
</template>

<script>
export default {
  data() {
    return {
      options: {
        scrollBar: false,
      }
    }
  },
}
</script>
```

My nuxt config
```javascript
  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    'nuxt-fullpage.js',
  ],
```

### Versions 

Vue  : 2.6.12
Nuxt : ^2.15.0

**Comment by alvarotrigo** [comment]
Make sure one of your sections has the `active` class.

**Comment by Anthony2511** [comment]
I added `active` class on one of my sections, but I still have the same problem.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by Anthony2511** [comment]
I resolved the problem. I forget to class `section` to childs sections. 
Thank for your help !

**Comment by alvarotrigo** [comment]
No problem!
