### ISSUE TITLE
duplicate active item in navigation after adding sections

### ISSUE THREAD

**Issue by dsheyp** [alvarotrigo/vue-fullpage.js#19]
i just noticed a minor oddity. when i scroll to section 3, add a 4th section (Add Section - Button), scroll to that 4th section, add another 5 sections - then from now on there will be duplicate active items in the navigation when scrolling to the 4th or 5th section. 

this can be seen in the codePen you mentioned in this answer #18 (https://codepen.io/alvarotrigo/pen/zpQmwq)

**Comment by alvarotrigo** [comment]
That's a bug on the demo, not on the component. 
Just remove the last item from the anchors option:

Change

```javascript
        anchors: ['page1', 'page2', 'page3', 'page4'],
```
To
```javascript
        anchors: ['page1', 'page2', 'page3'],
```
