### ISSUE TITLE
paddingTop is doesn't work when i slide up

### ISSUE THREAD

**Issue by DDYMZL** [alvarotrigo/vue-fullpage.js#190]
I set paddingTop: 100px
When I'm sliding down

![image](https://user-images.githubusercontent.com/37839057/113997407-b1278c80-988a-11eb-95b4-8585dc8d63ab.png)

but when i slide up

![image](https://user-images.githubusercontent.com/37839057/113997456-bdabe500-988a-11eb-843b-1e5f265dc7d4.png)

### Versions 
"vue-fullpage.js": "^0.1.7"
macOs 11.2.1

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
I'll close the issue until an isolated reproduction is provided.
