### ISSUE TITLE
Sections are jumped over when using menu and anchors with NuxtJS

### ISSUE THREAD

**Issue by desirelabs** [alvarotrigo/vue-fullpage.js#195]
### Description
Using `menu` and `anchors` options on nuxt makes the navigation and scrolling jump some sections.

In the provided example (see below), clicking on 'services' jumps straight to the 'pictures' section. Scrolling does the same.
A new block appears at the end of sections. Scrolling back from that point jumps over the last real section 'contact'

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/embed/github/desirelabs/nuxt-with-fullpage/tree/main/?fontsize=14&hidenavigation=1&theme=light

### Steps to reproduce it
1. Following the steps described [here](https://github.com/alvarotrigo/vue-fullpage.js#usage-with-nuxtjs)
2. Create a menu with an id and links with `href` targets, wrapped in `data-menuanchor`
3. implement sections as described [here](https://github.com/alvarotrigo/vue-fullpage.js#using--component)

### Versions 
Chrome 91.0.4472.106
nuxt-fullpage.js 0.0.3
fullpage.js 3.1.2

**Comment by alvarotrigo** [comment]
As pointed out on the <a href="https://github.com/alvarotrigo/fullPage.js" target="_blank">fullpage.js documentation</a> as well as on your JS console:

> Be careful! `data-anchor` tags can not have the same value as any `ID` element on the site (or `NAME element for IE).

**Comment by desirelabs** [comment]
Sorry, my bad.
