### ISSUE TITLE
Was not able to scroll properly on iOS

### ISSUE THREAD

**Issue by sneko** [alvarotrigo/vue-fullpage.js#198]
Hi,

I solved my issue but I leave it here for the record 👍 

## Issue

Everything was working great with the plugin on all platforms except inside Safari on iOS. For whatever reason after the init, when I tried to scroll by touching a text nothing happened (except randomly, but that's rare), but if I touched a blank area to scroll there is no issue at all.

## Solution

~~I investigated during hours (seriously), removing piece by piece and some hair... I finally found the tiny thing making things breaking:~~
* ~~inside my `App.vue` I had a `<div id="app">` whereas I already have one into my `index.html`, it seems they were conflicting when `vue-fullpage.js` is used.~~

~~I fully understand only one of this ID should exist, I missed it in the past because my other repos are using `ionic-app` (Ionic) or `v-app` (Vuetify), but not this one. And didn't notice this since no weird behavior for years with this repository, except since I'm using FullPage.js~~

~~I'm not able to explain the origin (I'm using server-side-rendering too, with an async init), but I hope it can help someone~~

**Comment by alvarotrigo** [comment]
Thanks for the explanation @sneko !! 👍

**Comment by sneko** [comment]
@alvarotrigo I was wrong, I posted too fast! During my tests it was working because it broke the whole Vue thing and FullPage.js was not initializing 😩  (was testing only on mobile and since I use `responsiveWidth` I thought everything was good now)

A new time I tried to reduce the possibilities and I figured it out a weird behavior:
```
<template>
  <div class="main-container">
    <client-only>
      <full-page :options="{ responsiveWidth: 768 }">
        <div class="section fp-auto-height-responsive">
          <div>WILL WORK<sup>1</sup></div>
          <div>WILL WORK <a>aaaaaaaaaaa</a></div>
          <div>NOT WORKING</div>
          <div><span>WORKING<span></div>
        </div>
        <div class="section fp-auto-height-responsive">
          <div>WILL WORK<sup>1</sup></div>
          <div>
            NOT WORKING
          </div>
          <div>NOT WORKING</div>
        </div>
      </full-page>
    </client-only>
  </div>
</template>

<script lang="ts">
  import ClientOnly from 'vue-client-only';
  import { Component, Vue } from 'vue-property-decorator';

  @Component({
    name: 'Home',
    components: {
      ClientOnly,
    },
  })
  export default class extends Vue {}
</script>

<style lang="css">
  .summary {
    font-size: 30px;
  }
</style>
```

I don't know if you have an iPhone (I'm using an iPhone 7), but I'm curious if you can reproduce this behavior (not able to scroll when touching the texts with "not working".

I will try to make a CodePen or something else soon... but spent too much time trying to catch the thing. I wrapped my code into "client-only" to be sure it does not come from the SSR, but will try with a raw project when possible.

Thanks,

**Comment by sneko** [comment]
@alvarotrigo I'm glad I was able to reproduce it into a simple Codepen (without SSR and so on)! You just need to start the scroll from a text with written "NOT WORKING". Please find it here: https://codepen.io/sneko7/pen/ZEyoZXx (sometimes it seems the browser accepts scrolling on them after some time and some attempts, if so to reset just refresh the page).

But to test it may be better with the full preview: https://codepen.io/sneko7/full/ZEyoZXx

Note that I tested on an iPhone 7 (first with iOS `v14.7.1` and today with `v14.8`).

Hope someone can help, I'm totally stuck after investigations 😄

**Comment by alvarotrigo** [comment]
The codepen won't even autoScroll on my iPhone 11. You are using `responsiveWidth: 768,`  and the iPhone has less than 768px width, so it enters into responsive mode.

I forked it and replaced it for `responsiveWidth: 268,` and I can't reproduce the issue on Safari/iPhone 11/iOS 14.2

I've also tested it on browserstack.com with a real device on iOS 14.4:
https://user-images.githubusercontent.com/1706326/134156490-aafda6ae-9226-46ec-95f9-146d67d9874c.mp4

![image](https://user-images.githubusercontent.com/1706326/134156497-63c28b66-cfab-4b44-8ef5-cfd99ec6825f.png)

**Comment by sneko** [comment]
@alvarotrigo maybe we misunderstood each other:

Indeed the plugin enters in its responsive mode due to the `768px` limit, that's totally wanted.

My issue is that I cannot use the basic scroll of the browser if a block `div` (containing text) does not contain an inline HTML tag.

In my Codepen you can see the difference between those noted as `WORKING` and those `NOT WORKING`. When I touch the `NOT WORKING` ones and swipe to make it scroll, it does not. This does not happen unless I add a workaround like an empty `<b></b>`.

Note that all cases will work on my Safari (iPhone 7, iOS 14) if I ask FullPage.js not to init. And also if I totally remove the plugin wrapper (like a raw page).

(I'm not able to record the screen with touches, which is sad because it would make it more clear. I will try to get another phone to record me trying to scroll)

**Comment by alvarotrigo** [comment]
> if a block `div` (containing text) does not contain an inline HTML tag.

All your NOT WORKING text in the codepen is wrapped by `<div>` tags.

**Comment by alvarotrigo** [comment]
I still can not reproduce the issue on responsive mode.
Here's the codepen I'm using:
https://codepen.io/alvarotrigo/pen/VwWdwzx

Video:
https://user-images.githubusercontent.com/1706326/134159387-77c3e65a-afd3-4737-bc4d-b69fb407831c.mp4

**Comment by sneko** [comment]
> All your NOT WORKING text in the codepen is wrapped by <div> tags.

@alvarotrigo yes they are "raw text" inside a div, like for `<div>Hello</div>` (will not work), there is no nested inline tag like `<div><span>Hello</span></div>` (will work).

> https://user-images.githubusercontent.com/1706326/134159387-77c3e65a-afd3-4737-bc4d-b69fb407831c.mp4

It's hard for me to know where you clicked for the `NOT WORKING`, because if you click just a bit aside it will work. Let's say it worked on your side, maybe there is a difference of Safari... ?


I recorded a demonstration, your exact Codepen https://codepen.io/alvarotrigo/pen/VwWdwzx : 

https://user-images.githubusercontent.com/8195958/134161405-a81e33ed-cc60-4e36-b980-859d7b502f1a.mp4

(sorry for the quality, GitHub asked to reduce < 10MB and with a wide recording... 😞 tell me if you want a better video quality)

**Comment by alvarotrigo** [comment]
Have you tried reproducing it outside codepen or any other iframe?

**Comment by sneko** [comment]
@alvarotrigo yes, I did the Codepen because it's happening on the project I'm working on (Vue.js project). But as you can see the Codepen includes nothing from Vue.js that's just raw JS for your plugin.

**Comment by sneko** [comment]
@alvarotrigo for years Apple makes Safari interpreting things weirdly compared to other browsers (either CSS, sometimes doing breaking changes on cookies... I saw a lot). They do their own way most of the time, and sometime we pay the consequences 🥲 

Anyway, I don't know what's the stack of things that makes Safari going wrong, maybe kind of CSS transforms done by FullPage.js (I remember without initializing the scroll works normally)... and I understand you cannot investigate more since that's really odd 👍 

Anyway for those who face this, just add blank tags like `<b></b>` on blocks where it stucks the scroll. It helps as a workaround and I guess it won't affect the indexing by crawlers (SEO).

Thanks for you time (leaving it open),
