### ISSUE TITLE
jQuery dependency?

### ISSUE THREAD

**Issue by iamdubx** [alvarotrigo/vue-fullpage.js#2]
I mean, really? Why? It make no sense. Vue + jQuery = retarded.

**Comment by alvarotrigo** [comment]
Well, if you want to use jQuery library in Vue.js, that's exactly what you'll have to do like it or not.
There's no workaround. 

You don't like it? Don't use it. Easy.

**Comment by iamdubx** [comment]
I was hoping this Vue-specific library got rid of jQ, that's it. I already starred it, but then saw dependency, so was frustrated, sorry.

**Comment by hackuun** [comment]
Yeah thanks. But its not recommended to use.

**Comment by alvarotrigo** [comment]
@hackuun I'm working in a new version, but will probably take a moth or more to be launched.
