### ISSUE TITLE
Compiling Error using parcel

### ISSUE THREAD

**Issue by ramon-plusb** [alvarotrigo/vue-fullpage.js#20]
I cannot compile my project due to strange errors because there are "..." in some lines in FullPage.vue

<pre>
....\node_modules\vue-fullpage.js\src\FullPage.vue:34:10: Unexpected token (34:10)
  32 |       events: constants.EVENTS.reduce((eventsHandlers, event) => {
  33 |         return {
> 34 |           ...eventsHandlers,
     |           ^
  35 |
  36 |           [event]: (...args) => {
  37 |             this.emitEvent(event, args);
</pre>

**Comment by alvarotrigo** [comment]
Make sure to see all dev dependencies in the [package.json file](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/package.json) and install them to run it with babel:

See how the provided examples are compiled on the package.json scripts section and the webpack.config.js files.

To compile a demo you'l have to use the following:
```shell
npm run-script demo1
```

**Comment by ramon-plusb** [comment]
Thanks for your fast response! I think that's too many dependencies for my project tho. Also I cannot expect from all my coworkers to go through the same procedure when they're trying to setup a dev environment. Sadly I'll have to look for another solution..

**Comment by alvarotrigo** [comment]
I believe this should be fixed in the latest version 0.0.2
