### ISSUE TITLE
$ is not defined: best way to import jQuery

### ISSUE THREAD

**Issue by Eelsie** [alvarotrigo/vue-fullpage.js#21]
Hello! I'm having problems importing jQuery, this is my imports: 
```
var $ = require('jquery')
  window.jQuery = $
  require('../vendor/fullpage/scrolloverflow.min.js')
  import * as fullpage from 'imports-loader?define=>false!../vendor/fullpage/fullPage'
  import FullPage from '../../node_modules/vue-fullpage.js/src/FullPage.vue'
```
I tryed also importing jQuery with ìmport $ from 'jquery'` but console still says `$ is not defined`.  What am I doing wrong? Thanks a lot!
![screen shot 2018-05-22 at 16 26 17](https://user-images.githubusercontent.com/11568278/40365311-eb541248-5ddc-11e8-9f7d-13e7f4c246db.png)

**Comment by alvarotrigo** [comment]
Have you taken a look at the [available examples](https://github.com/alvarotrigo/vue-fullpage.js/tree/master/demos)?

See also [the webpack.config file](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/webpack.config.js) and the [package.json file](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/package.json).
