### ISSUE TITLE
In nuxt, custom component not working inside fullpage

### ISSUE THREAD

**Issue by joshephan** [alvarotrigo/vue-fullpage.js#217]
### Description

package.json

{
   ...,
  "dependencies": {
    "core-js": "^3.15.1",
    "node-sass": "^6.0.1",
    "nuxt": "^2.15.7",
    "nuxt-fullpage.js": "^0.0.3",
    "sass-loader": "10",
    "vue-fullpage.js": "^0.1.7"
  },
  "devDependencies": {
    "@nuxt/types": "^2.15.7",
    "@nuxt/typescript-build": "^2.1.0",
    "vuex-module-decorators": "^2.0.0"
  }
}

I created nuxt app and installed vue-fullpage.js with nuxt-fullpage.js.
In development environment, it works fine.
But after create static website with "yarn generate", deployment website returns error.

<img width="390" alt="스크린샷 2021-12-03 오후 4 24 43" src="https://user-images.githubusercontent.com/4365470/144562084-9acca958-f32a-48bf-83a5-d4e0bd2aa1a0.png">

my code looks like below:

```
<no-ssr>
      <full-page ref="fullpage" :options="options">
        <custom-component></custom-component>
        <custom-component></custom-component>
        <custom-component></custom-component>
      </full-page>
</no-ssr>
```

Each components file's code looks like this:

```
<template>
  <div class="section">
    ... something inside
  </div>
</template> 
```

I've read issues like [133](https://github.com/alvarotrigo/vue-fullpage.js/issues/138), [140](https://github.com/alvarotrigo/vue-fullpage.js/pull/140). But it's not working for me.

deployed link is: [https://main.d10q0n4sejfpsv.amplifyapp.com/](https://main.d10q0n4sejfpsv.amplifyapp.com/)

**Comment by alvarotrigo** [comment]
Did you manage to solve the issue?
I can't see any console error in https://main.d10q0n4sejfpsv.amplifyapp.com/.

Also, can you reproduce the issue in on the demo?
https://github.com/alvarotrigo/vue-fullpage.js/tree/master/demos/webpack

Or in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code?

**Comment by joshephan** [comment]
Yes I solved this issue just before reply added.  :) 

My answer is added `:skip-init=true`. 
And after mount. 

`settimeout(()=> this.$refs.fullpage.init()).`

It works for me.

**Comment by alvarotrigo** [comment]
Thanks for the info! :)
