### ISSUE TITLE
In Nuxt targer: static build, fullpage is not working

### ISSUE THREAD

**Issue by SupriyaGo** [alvarotrigo/vue-fullpage.js#229]
I have created a nuxt project and I am using vue-fullpage there. When I am doing static build of my application, full-page is not working, my web page is looking like a simple scrollable website.

**Comment by alvarotrigo** [comment]
Did you read about how to use vue-fullpage.js with nuxt ?
https://github.com/alvarotrigo/vue-fullpage.js#usage-with-nuxtjs

Also, make sure to check the available examples.

Note this won't work with Vue3. We are working on that for the next version.
So far you can try to use the [new version in development](https://github.com/alvarotrigo/vue-fullpage.js/tree/next) if you want.

**Comment by SupriyaGo** [comment]
@alvarotrigo I followed every step but still its not working when doing static build. Please help

**Comment by alvarotrigo** [comment]
Try to provide an isolateds reproduction in codesandbox. That'd make it easier for us to check.

**Comment by SupriyaGo** [comment]
[https://codesandbox.io/s/nifty-keldysh-qyttvw](url)

This is my code.

Please run -
npm run generate 
npm run start

**Comment by SupriyaGo** [comment]
![image](https://user-images.githubusercontent.com/40319687/155517519-b0e5409f-5ca7-4106-a933-153b11561207.png)
Here it is coming [object object] 
@alvarotrigo
