### ISSUE TITLE
onLeave return false does not work

### ISSUE THREAD

**Issue by vinkodlak** [alvarotrigo/vue-fullpage.js#23]
Hi there!

Seems like return false from onLeave callback does not work on vue-fullpage.js
It works on non vue version like described, but here it just does not cancel the scroll

```javascript
data() {
  return {
    options: {
      onLeave: this.onLeave,
      ...
    }
  }
},
methods: {
  onLeave(i,n,d) {
    console.log('Leave event: ', i, n, d)
    return false
  }
}
```
onLeave is fired, and console log works, but it does not cancel the scroll after.

Am I missing something? Thnx

**Comment by alvarotrigo** [comment]
I'll try to take a look at it in the next week!

**Comment by JWardee** [comment]
@vinkodlak just came across this issue myself, my fix is in pull request #25 if that's of any help

**Comment by mofman** [comment]
anywork arround for this? thanks

**Comment by alvarotrigo** [comment]
This works perfectly for me on the latest vue-fullpage.js version. 
I can not reproduce the issue. 

This is my setup:

```javascript
 export default {
    name: 'app',
    data () {
      return {
        options: {
          onLeave: this.onLeave,
          sectionsColor: ['#41b883', '#ff5f45', '#0798ec']
        }
      }
    },
    methods: {
      onLeave (origin, destination, direction){
        console.log("leaving...");
        console.log("destination");
        return window.juan ? window.juan : false;
      },
    }
  }
```

**Comment by alvarotrigo** [comment]
Check this [reproduction online](http://jsfiddle.net/175czw8u/5/).

**Comment by mofman** [comment]
You are correct but I cant understand why the below code wont work

Ive set animationIsFinished to false and it only changes to true once setTimeout is finished?

    if (nextIndex.index == 1 && direction == 'down') {  

    	var self = this;
    	setTimeout(function(){
    		console.log('load');
    		self.animationIsFinished = true;
    	}, 2000);

    }

    return this.animationIsFinished;

**Comment by mofman** [comment]
You are correct

Although I cant seem to make this work?

	 onLeave (origin, destination, direction){

	    console.log(this.animationIsFinished);

	    if (destination.index == 1 && direction == 'down') {  

	    	var self = this;
	    	setTimeout(function(){
	    		console.log('load');
	    		self.animationIsFinished = true;
	    		return true;
	    	}, 2000);

	    }

	    return this.animationIsFinished; 

	}

**Comment by alvarotrigo** [comment]
Try to provide an isolated reproduction by creating your issue on this fiddle: http://jsfiddle.net/175czw8u/5/

**Comment by mofman** [comment]
Thanks

http://jsfiddle.net/175czw8u/13/

**Comment by alvarotrigo** [comment]
You should return true on the callback, not inside the timeout function.

**Comment by mofman** [comment]
Sorry that was an attempt

I've also tried returning true on the callback
http://jsfiddle.net/175czw8u/17/

**Comment by alvarotrigo** [comment]
The callback is only executed once per scroll. So it will only be executed once with `false`and the change in the timeout will have no consequence at all until the next scroll event. 

You can do this instead:

```javascript
          setTimeout(function(){
              console.log('load');
              self.waitLoad = true;
              fullpage_api.moveTo(destination.index + 1);
          }, 1000);
```

See the fiddle:
http://jsfiddle.net/175czw8u/20/
