### ISSUE TITLE
vue fullpage footer not scrolling as its height.

### ISSUE THREAD

**Issue by candijun** [alvarotrigo/vue-fullpage.js#235]
### Description
vue fullpage footer not scrolling as its height, it is fully scrolling.

### Link to isolated reproduction with no external CSS / JS 
(https://codesandbox.io/s/morning-sea-p0prdo?file=/src/App.vue)

### Versions 
chrome latest version, vue 2.6.11

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
We'll be investigating it.

**Comment by candijun** [comment]
> Thanks for reporting it! We'll be investigating it.

Hello! alvarotrigo! Thank you for response.

I am preparing to open the site using vue-fullpage but before that I want to ask if it was about to solve.

**Comment by alvarotrigo** [comment]
> I am preparing to open the site using vue-fullpage but before that I want to ask if it was about to solve.

Yeah, the issue here is that you are loading the fullpage.css file for version 4 but vue-fullpage.js still uses fullPage.js version 3.

So make sure to load version 3.
