### ISSUE TITLE
How can i destroy fullpage.js when i go to another page?

### ISSUE THREAD

**Issue by cheulong** [alvarotrigo/vue-fullpage.js#24]
When i go to another page and click back button on the browser. The fullpage scroll doesn't work any more? Help

**Comment by cheulong** [comment]
I figured it out already, I putted **$.fn.fullpage.destroy('all');** in **destroyed() {}** but i dont know if it is the right to do it or not.

## destroyed() {
  ##   $.fn.fullpage.destroy('all');
  ## }

**Comment by cheulong** [comment]
I make a video to step by step to make it works. Hope it will work for you all.

[https://youtu.be/MORCeDt5dJ4](url)

**Comment by alvarotrigo** [comment]
Yeah you can destroy it by using the `destroy` method.
Now with fullPage.js version 3:

```javascript
fullpage_api.destroy('all');
```
