### ISSUE TITLE
Vue 2

### ISSUE THREAD

**Issue by dickyjayaumbara** [alvarotrigo/vue-fullpage.js#255]
Hei this awesome plugin, can this plugin still worked with Vue 2, if not, can i get link for Vue 2 version.

**Comment by alvarotrigo** [comment]
Sure, you can try version 0.1.5, but that won't include the latest fullPage.js version either. 

https://github.com/alvarotrigo/vue-fullpage.js/releases/tag/0.1.5

**Comment by mattgilbertnet** [comment]
@alvarotrigo Is it possible to use fullPage.js 4 with vue-fullpage in Vue 2? (Migrating an existing app from Vue 2 to 3 can be quite involved, especially with popular dependencies like Vuetify still not supporting Vue 3.)

**Comment by alvarotrigo** [comment]
> @alvarotrigo Is it possible to use fullPage.js 4 with vue-fullpage in Vue 2?

I haven't tried it myself, but I invite you to give it a try :)
From our side, we don't provide support for it. I can only recommend you keep using fullPage.js v3.

**Comment by mattgilbertnet** [comment]
I gave it a shot, by forking vue-fullpage before vue 3 changes, and just changing the fullpage.js version. But `build:browser` hangs.

https://github.com/mattgilbertnet/vue-fullpage.js

**Comment by alvarotrigo** [comment]
Sorry but I can't assist you there.
We only provide support for the latest version.

**Comment by alvarotrigo** [comment]
Try `npm run build` or `npm run dev`

**Comment by guda-art** [comment]
sry,  version 0.1.5 can  work with vue2.x perfectly ? thankyou.

**Comment by guda-art** [comment]
version 0.1.5 can use all options in https://github.com/alvarotrigo/fullPage.js#options

**Comment by alvarotrigo** [comment]
Version 0.1.5 uses fullPage.js 3.1.2 instead of fullPage.js 4.0.15.
So you should go to version 3 docs:

https://github.com/alvarotrigo/fullPage.js/tree/3.1.2

**Comment by alvarotrigo** [comment]
Version 3 is no longer maintained or supported.

**Comment by guda-art** [comment]
> Version 0.1.5 uses fullPage.js 3.1.2 instead of fullPage.js 4.0.15. So you should go to version 3 docs:
> 
> https://github.com/alvarotrigo/fullPage.js/tree/3.1.2

thankyou verymuch !

**Comment by guda-art** [comment]
My project uses vue2+nuxt.js. After reading all the information, I think vue-fullpage.js v0.1.5 is the only one that can be applied to my project Do you have any better suggestions?

**Comment by guda-art** [comment]
@alvarotrigo

**Comment by alvarotrigo** [comment]
No

**Comment by guda-art** [comment]
> No

Thanks anyway
