### ISSUE TITLE
Can't find my profesional licence key for fullpage.js?

### ISSUE THREAD

**Issue by mattesowah** [alvarotrigo/vue-fullpage.js#259]
Hi there,

so this isn't really much of a technical issue but I was wondering where can I access my license key once I have purchased it from the gumroad link, as it doesn't seem to be located in the file I downloaded?

**Comment by mattesowah** [comment]
never mind just checked my email thanks once again

**Comment by alvarotrigo** [comment]
Glad you figured it out :)
