### ISSUE TITLE
render function or template not defined in component: anonymous

### ISSUE THREAD

**Issue by 44886** [alvarotrigo/vue-fullpage.js#26]
![image](https://user-images.githubusercontent.com/10481933/41499571-caa67234-71b4-11e8-8b71-4c8ca2ce5359.png)

**Comment by alvarotrigo** [comment]
I'm about to make a big change in the component. Hopefully in a week.
Let's see if then you still have the error !

**Comment by alvarotrigo** [comment]
Can you verify if you still having this issue with the latest vue-fullpage.js version 0.0.3?
