### ISSUE TITLE
vue-fullpage.js package not working in Codepen

### ISSUE THREAD

**Issue by versionmj** [alvarotrigo/vue-fullpage.js#260]
### Description

vue-fullpage.js package does not appear to be working codepen.  

Thx.

### Link to isolated reproduction with no external CSS / JS

My Attempt:

https://codepen.io/dresscode/pen/ZERjLxY

Official wrapper demo:

https://codepen.io/alvarotrigo/pen/zpQmwq

### Versions

[Chrome Version 107.0.5304.110, Mac OS Monterey V. 12.0.1, ]

**Comment by alvarotrigo** [comment]
The codepen wasn't maintained and that's for the older version of vue-fullpage.js

You can find a working demo here:
https://github.com/alvarotrigo/vue-fullpage.js/tree/master/example

@JonathanSchndr I guess we'll have to update the codepen for the new Vue version?
I've given it a try but I'm sure I'm missing something :) 
https://codepen.io/alvarotrigo/pen/poKZQNG

**Comment by alvarotrigo** [comment]
> Given that we already have this Issue thread open and I can’t use codepen to create a reproduction, I may as well ask you about this issue here.

You can use codesandbox.
https://codesandbox.io/s/practical-danilo-sf5y1h?file=/package.json

**Comment by JonathanSchndr** [comment]
Hey! Gladly I can support, unfortunately I'm not quite clear yet where I can help. If I get a sandbox with the error, I can gladly develop a solution. Currently it is difficult for me to reproduce the problems of the different topics.

**Comment by alvarotrigo** [comment]
@JonathanSchndr I was trying to [create a demo on Codepen](https://codepen.io/alvarotrigo/pen/poKZQNG) using Vue with the [standalone way of using Vue](https://vuejs.org/guide/extras/ways-of-using-vue.html) but I'm not sure what I'm missing there to make it work.

We [had a codepen version with Vue2 on vue-fullpage.js 0.1.5](https://codepen.io/alvarotrigo/pen/zpQmwq) and it'd be great to have one with Vue 3 for the latest version of vue-fullpage.js 0.2.X in order to simplify the reproduction of certain issues.

**Comment by versionmj** [comment]
@JonathanSchndr and @alvarotrigo,  I've attempted to create a reproduction on codesandbox but the application doesn't want let me access the Vue Router.  At least this will help me describe what's happening and maybe you can extrapolate a solution. 

https://codesandbox.io/s/nervous-fire-swwp8r?file=/src/App.vue

My app has two pages "/webstore" and "/product" (though I have only produced a simplified version of the product page here). The fullpage component is contained in a Layout that is used on both pages, but section 0 is only relevant on the /webstore page.  So on arrival to the /product page, section 1 is active and I set autoScrolling(false) and overflow: hidden so the user cannot scroll up (cliick SCROLL LOCK  button in codesandbox to replicate).

Within the product page, each item has it's own route.  As a user clicks 'Next' and 'Prev' buttons another item is displayed and I am pushing a new route the vue-router without reloading or re-rendering the page (see lines 106 and 115 in App.vue - commented out because of condesandbox vue-router issue).

This works fine in my app except that when autoScrolling is set to false and a new route is pushed, the fullpage component sets section 0 to 'active' and the page jumps to the empty section.  I have isolated the issue within my app and it's clear that fullpage is only conflicting with the $router.push method when autoScrolling is off.  i.e. With autoScrolling on there is no jumping to section 0.

I hope that's clear.

Thanks.

**Comment by versionmj** [comment]
@JonathanSchndr and @alvarotrigo any thoughts on this?  eg. Is there any reason why pushing a new route would cause fullpage to jump to section 0?  Any suggestions would be appreciated.

**Comment by JonathanSchndr** [comment]
> @JonathanSchndr and @alvarotrigo any thoughts on this? eg. Is there any reason why pushing a new route would cause fullpage to jump to section 0? Any suggestions would be appreciated.

I looked at your sandbox and could see that you are not loading the router correctly. Since you don't have a createRoute instance, you can't access it: https://router.vuejs.org/guide/#javascript

I hope this info helps you!
