### ISSUE TITLE
Error in slides scroll more slides than total count nuxtjs3

### ISSUE THREAD

**Issue by leccyril** [alvarotrigo/vue-fullpage.js#264]
Hi, 

Here i set 11 sections and one menu components in the main page

at the end of slides you can scroll 1 more position (does not exists) then you will be blocked in it (black screen)

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by leccyril** [comment]
i tried this option

`  credits: { enabled: false },`
it is not false by default ?

**Comment by leccyril** [comment]
https://codesandbox.io/p/sandbox/vibrant-thunder-9tuyly

here ze can see insteaf of scrolling into 11 slide and display footer, you can scroll one below the last slide and you zill be blocked , then no footer displayed

**Comment by alvarotrigo** [comment]
I can't see anything rendered on the browser in the codesandbox:

![image](https://github.com/alvarotrigo/vue-fullpage.js/assets/1706326/39d94045-b2a0-4fbe-9517-b6a31174a053)

**Comment by leccyril** [comment]
on the page you can launch new terminal and yarn dev
![image](https://github.com/alvarotrigo/vue-fullpage.js/assets/3234598/34657a4e-d9d7-404a-9b00-7039936c52e7)

you can also test on this URL

https://9tuyly-3001.csb.app/

**Comment by alvarotrigo** [comment]
> Can you access to it ?

Yeap.

The text "TESTESTEST" has to be placed in a fixed element to prevent from increasing the size of the viewport. 

I've fixed this on the latest version 0.2.14 of vue-fullpage.js
You can download it from npm

**Comment by leccyril** [comment]
hi, the version i use is this 

"@fullpage/nuxt-fullpage": "^0.2.3",

it is not existing yet on npm :

https://snipboard.io/PNejnK.jpg

Could you make the fix for this too ?

it will be working if we add also a footer ?

Thank you for teh reactivity

**Comment by alvarotrigo** [comment]
Can you try again with @fullpage/nuxt-fullpage 0.2.4?
Thanks.

**Comment by leccyril** [comment]
it is ok now and working :)

PS : if i add a footer it will work also ?

**Comment by alvarotrigo** [comment]
> PS : if i add a footer it will work also ?

The footer should ideally be inside the fullPage.js structure.
Just another section using `fp-auto-height` class.
See this example:
https://alvarotrigo.com/fullPage/examples/autoHeight.html

**Comment by alvarotrigo** [comment]
> great juste one question i dont know where to put it, i want to add moveToTop button but i dont know how to implement with nuxtjs

See the docs regarding how to use methods:
https://github.com/alvarotrigo/vue-fullpage.js#methods

There's not method called `moveToTop`.
Use `moveTo(1)` instead.

**Comment by leccyril** [comment]
it is just the wrapper method ^^

/*this is not working*/
function moveToTop(){
	fullpage_api.moveTo('SectionIntro1', 1);
}

but fullpage_api does not existe i will check thanks and send you website done with ur great module
