### ISSUE TITLE
Vite HMR not working with vue fullpage

### ISSUE THREAD

**Issue by cuberinooo** [alvarotrigo/vue-fullpage.js#267]
### Description
Doing changes on the <script></script> on a vue component which is inside the ```<Fullpage> ``` component causes an error.

Imaging having the following structur:

```
<FullPage>
 <SomeVueComponent></SomeVueComponent> 
</FullPage>

//Inside the SomeVueComponent
<div class="section">
...
</div>
```

So whenever I change on the <script></script> part on the SomeVueComponent  and let HMR update or render the page the next thing I get is the following error:

vue-fullpage.mjs:463 Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at ai.ri (vue-fullpage.mjs:463:125)
    at new ai (vue-fullpage.mjs:495:10)
    at ye (vue-fullpage.mjs:563:53)
    at Object.onLeave (vue-fullpage.mjs:573:28)
    at vue-fullpage.mjs:585:19
    at se (vue-fullpage.mjs:586:7)
    at Xe (vue-fullpage.mjs:795:241)
    at pt (vue-fullpage.mjs:1119:86)
    at _i (vue-fullpage.mjs:1133:187)
    at HTMLDocument.Ke (vue-fullpage.mjs:1358:136)

It seems that fullpage is not recognizing the changes and therefore it can not query on the dom since the elements are missing. (Changes on script section recreates the component)

After hard refreshing the page it works. Anyone has also same issues with HMR ?

**Comment by alvarotrigo** [comment]
What version are you using of vue-fullpage?

**Comment by alvarotrigo** [comment]
Have you tried destroying fullPage.js and initializing it again after you make the changes on the DOM.

**Comment by cuberinooo** [comment]
Im using 0.2.15

I could rerender the fullpage-component but how do I apply this to HMR ? How do I interrupt the hot reload process and destroy and init the component again or let`s say it how am I able to destroy and init the fullPage.js when hmr is triggered ?

**Comment by alvarotrigo** [comment]
> How am I able to destroy and init the fullPage.js when hmr is triggered ?

I'm not familiar with HMR, but you can destroy fullpage.js using `fullpage_api.destroy('all');` and initialise it again after that.

**Comment by cuberinooo** [comment]
I found a possible solution for that. In Vite you can use the hmr api see here: https://vitejs.dev/guide/api-hmr.html#hot-on-event-cb

What I do is I rebuild the component as you suggest whenever afterUpdate is triggered :

```
// This can be placed anywhere on your vue app

  import.meta.hot.on('vite:afterUpdate', () => {
    fullpage.value.destroy();
    fullpage.value.init();
  })

```

With that it seems hot reloading with no side effects is working again. Thank you !

**Comment by alvarotrigo** [comment]
> With that it seems hot reloading with no side effects is working again. Thank you !

Awesome! 🥳 
Glad you managed to find a solution!
