### ISSUE TITLE
Unexpected token *

### ISSUE THREAD

**Issue by 44886** [alvarotrigo/vue-fullpage.js#27]
I use it in nuxt ,but it shows this:
![image](https://user-images.githubusercontent.com/10481933/41499614-5aaa7b46-71b5-11e8-8f88-063fc2fc01cb.png)

this is my code:
![image](https://user-images.githubusercontent.com/10481933/41499616-649c8978-71b5-11e8-8c25-500c0ea55e63.png)

**Comment by alvarotrigo** [comment]
Can you verify if you still having this issue with the latest vue-fullpage.js version 0.0.3?

**Comment by alvarotrigo** [comment]
Closed until proved it stills there.
