### ISSUE TITLE
The afterLoad callback does not work

### ISSUE THREAD

**Issue by renjd** [alvarotrigo/vue-fullpage.js#271]
### Description
I have followed the document requirements but failed. I am considering whether it is due to the sub components. Please provide a solution, thank you!The relevant code is placed below:

![20240327184330](https://github.com/alvarotrigo/vue-fullpage.js/assets/165153801/97e43dde-6e33-4ffb-87c3-c8b12a441ae6)
![20240327184409](https://github.com/alvarotrigo/vue-fullpage.js/assets/165153801/5c648942-c113-4421-9803-04ddbbfebd30)

**Comment by renjd** [comment]
I have just started learning front-end technology, so the code is very ugly. Please understand and look forward to your reply！

**Comment by alvarotrigo** [comment]
You can take a look at the code of the example:
https://github.com/alvarotrigo/vue-fullpage.js/tree/master/example

That's working properly. 
You can use it as a base to work on.

**Comment by alvarotrigo** [comment]
Also, you seem to be missing `data-anchor` on section 1.

**Comment by alvarotrigo** [comment]
And I see you are overwriting fullPage.js styles by using `position:absolute` on the slides. 
You shouldn't be doing that. Otherwise fullPage.js might not work as expected.

**Comment by renjd** [comment]
> Also, you seem to be missing `data-anchor` on section 1.

Because I want to change the animation effect when switching pages, the first page already has an animation by default, so I did not add a data anchor on the first page. Thank you for your series of replies, I will try again later.

**Comment by renjd** [comment]
> Also, you seem to be missing `data-anchor` on section 1.

When the fullpage component is loaded, all its subcomponents are also rendered, which means that even if I add animation elements to other pages, these animations are actually played on the first page. Therefore, sliding on to the second and third pages, the animation effect is no longer visible.

**Comment by renjd** [comment]
> And I see you are overwriting fullPage.js styles by using `position:absolute` on the slides. You shouldn't be doing that. Otherwise fullPage.js might not work as expected.

Thank you for your help. The reason is that I mixed scripts for Vue2 and Vue3, which should be the reason for this. I may not be able to express myself clearly, but I am still very grateful to you and wish you a happy life!
——A freshman student from China

**Comment by alvarotrigo** [comment]
Awesome that you managed to find the problem! 🥳 

Regards from Spain!
