### ISSUE TITLE
About the issue of sliding page screenshots

### ISSUE THREAD

**Issue by renjd** [alvarotrigo/vue-fullpage.js#272]
### Description
How to use a screenshot plugin like html2canvas to complete an overall screenshot of a sliding page, including the first to last pages

**Comment by alvarotrigo** [comment]
I'm not familiar with html2canvas so I'd recommend you ask in [their repository](https://github.com/niklasvh/html2canvas/issues).

You might want to try using `scrollBar:true` in case it helps.
