### ISSUE TITLE
Need help with Vue2.x version(Just purchased a new license)

### ISSUE THREAD

**Issue by troycn** [alvarotrigo/vue-fullpage.js#273]
### Description
Dear @alvarotrigo,

I'm a new developer of our website, the old license can't be used, so we purchased a new license for it.
But this site used a old version of `vue-fullpage.js` at `0.1.7` to compatible for `Vue` `2.6.12`.
When I changed the licenseKey variable for vue.fullpage.js from `28xxxxxx-762Bxxxx-8869xxxx-36xxxxxx` to `BMVXX-5QXXX-K4XXX-A4XXX-MVPYM`, I found the license's string pattern has changed, then I got an error in console:
> fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:
> fullPage: https://github.com/alvarotrigo/fullPage.js#options

Please give me some guidance for the license's effectiveness, or how should I change my vue-fullpage.js version without update the Vue core version to 3.x.

### Link to isolated reproduction with no external CSS / JS

Considering the license problem, I can't deliver the reproduction code.

### Versions

Browser:  Chrome 129.0.6668.60
Operating system: Windows 11
Used Package Version: 
    - vue-fullpage.js@0.1.7
    - vue@2.6.12
    - vue-cli@4.5.12

Thanks for your help.

**Comment by troycn** [comment]
I also deliver a ticket in [contact](https://alvarotrigo.com/contact/) form, feel free to contact me with email.

**Comment by alvarotrigo** [comment]
Fixed on the ticket system ;)
