### ISSUE TITLE
fullpage 3.x.x

### ISSUE THREAD

**Issue by dazpinto** [alvarotrigo/vue-fullpage.js#29]
Hi

Is there any plan to upgrade this project to use the new release of fullpage without jQuery? 

If so any ideas on timescales?

Thanks

**Comment by alvarotrigo** [comment]
Yeap!!
Less than 3 weeks for sure!

**Comment by dazpinto** [comment]
Great thanks!

**Comment by andy-noir** [comment]
@alvarotrigo , is there any possibility that the documentation will get updated (regarding installation)?

**Comment by alvarotrigo** [comment]
Fixed on the latest version 0.0.2.
Now compatible with fullpage.js v3.
