### ISSUE TITLE
Module parse failed: Unexpected token @ fullpage.vue

### ISSUE THREAD

**Issue by SueIte** [alvarotrigo/vue-fullpage.js#31]
I tried integrating my vue-fullpage.js component since Iam rebuilding an original website with Vue.js.

So I followed the Tutorial and there is 1 Error I can't seem to fix when importing 
"import FullPage from 'vue-fullpage.js'":

> ERROR in ./node_modules/vue-fullpage.js/src/FullPage.vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <!--
|  * vue-fullpage.js - fullPage.vue
|  * https://github.com/alvarotrigo/vue-fullpage.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Modules/FullpageSections/Section1.vue 246:0-39
 @ ./src/components/Modules/FullpageSections/Section1.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/App.vue
 @ ./src/components/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.js ./src/assets/scss/main.scss

My Package.json looks like this:

{
  "name": "pialconsult",
  "version": "1.0.0",
  "description": "homepage",
  "scripts": {
    "start": "webpack-dev-server",
    "build": "webpack"
  },
  "author": "PiAl",
  "devDependencies": {
    "autoprefixer": "^8.6.5",
    "axios": "^0.16.2",
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-3": "^6.24.1",
    "babel-runtime": "^6.25.0",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^0.11.2",
    "node-sass": "^4.9.2",
    "postcss-loader": "^2.1.5",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "vue": "^2.4.2",
    "vue-axios": "^2.0.2",
    "vue-loader": "^13.0.5",
    "vue-router": "^2.7.0",
    "vue-template-compiler": "^2.4.4",
    "webpack": "^3.12.0",
    "webpack-dev-server": "^2.9.1"
  },
  "dependencies": {
    "bootstrap": "^4.1.1",
    "jquery": "^3.3.1",
    "popper.js": "^1.14.3",
    "vue-fullpage.js": "0.0.1"
  }
}

Snippet from the Webpack.config.json:
```
{
                // Ask webpack to check: If this file ends with .vue, then apply some transforms
                test: /\.vue$/,
                // don't transform node_modules folder (which don't need to be compiled)
                exclude: /(node_modules|bower_components)/,
                // Transform it with vue
                use: {
                    loader: 'vue-loader',
                    options: {
                        loaders: {
                            'scss': 'vue-style-loader!css-loader!sass-loader',
                            'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax',
                            'js': 'babel-loader'
                        }
                    }
                }
            }
```

**Comment by alvarotrigo** [comment]
This should be now fixed on the latest version 0.0.2
