### ISSUE TITLE
Errors while Installing the Webpack demo

### ISSUE THREAD

**Issue by Tech-Nomad** [alvarotrigo/vue-fullpage.js#38]
Hey,
the described installation steps for webpack demo are leading to errors in my case. 

Only after removing package-lock.json file in the demos/wepback directory and running the command  `npm install --save vue-fullpage.js` I could finally run `npm install` without any errors and then `npm run dev` lead to the functioning demo

**Comment by alvarotrigo** [comment]
Yeah probably related to https://github.com/alvarotrigo/vue-fullpage.js/issues/37
I'll merge the dev version today to fix those issues.

**Comment by alvarotrigo** [comment]
Fixed in vue-fullpage.js 0.0.4
