### ISSUE TITLE
Cannot find module "vue-fullpage" when installing via NPM

### ISSUE THREAD

**Issue by itzikbenh** [alvarotrigo/vue-fullpage.js#41]
I got this error both on versions 0.0.3 and 0.0.4.

I'm using Webpack if it matters.

**Comment by alvarotrigo** [comment]
At which point you get this error? 
I'm not able to reproduce your issue.

I'm using the `demos/webpack/` example to try to reproduce it. Everything is working fine, `npm run build` creates the `demos/webpack/dist/build.js` file  and then it runs smoothly on the `demos/webpack/index.html` page.

**Comment by itzikbenh** [comment]
I get it simply by doing `import VueFullPage from 'vue-fullpage';` Tried some other combinations, but they didn't work. My other imports works just fine, including fullpage.js

Eventually I just copied the code from here, so it's a not a big deal for me, but I imagine something is wrong, but if you can't reproduce it then I guess you should wait and see if others get it. 
Thanks for responding.
