### ISSUE TITLE
How to set licenseKey? 

### ISSUE THREAD

**Issue by echozhangzy8888** [alvarotrigo/vue-fullpage.js#42]
I use this libray , and following document to run my project
fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. 
message
How to set licenseKey???
thanks!!!

**Comment by alvarotrigo** [comment]
As detailed in the fullpage.js docs, that's just another option more. 
Pass it on the options object.

For example, using it on the .vue file:

```javascript
export default {
    name: 'app',
    data () {
      return {
        options: {
          licenseKey: 'YOUR_KEY_HERE',
          afterLoad: this.afterLoad,
          scrollBar: false
        }
      }
    },
```

Or directly on the vue instance:
```javascript
new Vue({
  el: '#app',
  name: 'app',
  data() {
    return {
      options: {
        menu: '#menu',
        licenseKey: 'YOUR_KEY_HERE',
        sectionsColor: ['#41b883', '#ff5f45', '#0798ec']
      },
    }
  },
```

**Comment by manuxdjent** [comment]
Hi, I've set the licenseKey like that and it doesn't work

```
import Vue from 'vue'
import App from './App.vue'
import 'fullpage.js/vendors/scrolloverflow'
import VueFullPage from 'vue-fullpage.js'
import  VueTyper  from 'vue-typer'

Vue.use(VueFullPage)
Vue.use(VueTyper)
Vue.config.productionTip = false

new Vue({
  render: h => h(App),
  data() {
    return {
      options: {
        licenseKey: 'OPEN-SOURCE-GPLV3-LICENSE'
      }
    }
  }
}).$mount('#app') 
```

**Comment by alvarotrigo** [comment]
Since vue-fullpage.js 0.1.1 which uses fullPage.js 3.0.4 you'll have to [contact me](https://alvarotrigo.com/#contact) if you need an open source license. 

You can however get a license by purchasing the commercial license for fullPage.js at https://alvarotrigo.com/fullPage/pricing

**Comment by n0umankhan** [comment]
@alvarotrigo dude how to set in react js ? i passed as option licenseKey: "my key" but still getting this error : Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here

**Comment by n0umankhan** [comment]
never mind i passed as prop and it is working fine for future if some one face the same pro here is the solution
 `<ReactFullpage
    licenseKey={'your key'}
    sectionsColor={['#282c34', '#ff5f45', '#0798ec']}
    render={({ state, fullpageApi }) => {
      return (
        <div>
          <div className="section">1</div>
          <div className="section">2</div>
          <div className="section">3</div>
        </div>
      );
    }}
  />`

**Comment by alvarotrigo** [comment]
@n0umankhan wondering why you didn't open the issue on the [react-fullpage repository](https://github.com/alvarotrigo/react-fullpage) 🤔

**Comment by n0umankhan** [comment]
i start using it today i was about to create own logic but than i search and found your plugin, buy that found this key error i thought you are passing option as props that's how it solved. i'll open next time there if found any other issue

**Comment by honyKing** [comment]
> I use this libray , and following document to run my project fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. message How to set licenseKey??? thanks!!!

licenseKey: 'gplv3-license'

**Comment by rush-all** [comment]
hi，in this page [https://alvarotrigo.com/fullPage/examples/scrolling.html] ,i want use key event (like up and down) to control page srcoll ,but not section1 to section 2 ,just setcion1 srcoll , can you help me? Looking forward to your reply, thank you very much

**Comment by rush-all** [comment]
i am so sorry for my job to forgot to answer you , but  thanks for your reply , i solve this problem , i rewrite yours keydown event ,so i can do what i want to do .thanks again!
