### ISSUE TITLE
Slide is overlapping next section

### ISSUE THREAD

**Issue by chrtz** [alvarotrigo/vue-fullpage.js#46]
### Issue: 
When I initialize a new project with sections and slides, the slides are always overlapping the upcoming section.

Two days ago, I opened an issue (#45) regarding scrollOverflow () as I thought the current issue might depend on this. After the issue was closed and scrollOverflow was added the right way, the overlapping issue still remains. Therefore, I thought it might depend on the used bulma/buefy frameworks, so I started from scratch. But nothing helped. The second slide is overlapping Section 4.

## App.vue
```
<template>
  <div id="app">
    <full-page :options="options" id="fullpage" ref="fullpage">
      <div class="section">
        <h2>Section 1</h2>
      </div>
      <div class="section">
        <h2>Section 2</h2>
      </div>
      <div class="section">
        <!-- section 3 -->
        <div class="slide"><h2>Slide 1</h2></div>
        <div class="slide"><h2>Slide 2</h2></div>
      </div>
      <div class="section">
        <h2>Section 4</h2>
      </div>
      <div class="section">
        <h2>Section 5</h2>
      </div>
      <div class="section">
        <h2>Section 6</h2>
      </div>
      <div class="section">
        <h2>Section 7</h2>
      </div>
    </full-page>
  </div>
</template>

<script>
import Vue from "vue";
import "fullpage.js/vendors/scrolloverflow";
import VueFullPage from "vue-fullpage.js";

Vue.use(VueFullPage);

export default {
  name: 'app'
};
</script>
```

## main.js
```
import Vue from "vue";
import App from "./App.vue";

Vue.config.productionTip = false;

new Vue({
  render: h => h(App)
}).$mount("#app");
```

### Used tools and versions:
**macOS:** 10.12.6
**Chrome:** 68.0
**Vue CLI:** 3.0
**Vue:** 2.5.17
**Vue-Fullpage.js:** 0.0.5

**Comment by alvarotrigo** [comment]
Are you also adding the required fullPage css file?

**Comment by alvarotrigo** [comment]
@chrtz yeap ok! I've named it on the docs!
