### ISSUE TITLE
Issues with v-if/v-show

### ISSUE THREAD

**Issue by rikkipitt** [alvarotrigo/vue-fullpage.js#48]
Hi there,

I've built a Vue app that has dynamic sections and uses Vuex. Some sections are shown and hidden according to user interaction (think wizard). However, when I call the following, all state seems to be broken... is it possible to moveSectionDown to the next visible section?

```
this.$refs.fullpage.build();
this.$refs.fullpage.api.moveSectionDown();
```
I've tried both v-show and v-if on the sub-components:

```
<template>
  <full-page ref="fullpage" :options="options" id="wizard">
    <component
      v-for="(c, index) in this.$store.state.components"
      :is="c.name"
      :parentRefs="$refs"
      v-if="c.visible"></component>
  </full-page>
</template>
```

Cheers in advance!
Rikki

**Comment by alvarotrigo** [comment]
> is it possible to moveSectionDown to the next visible section?

Nop. Fullpage.js doesn't provide such feature. There's [an open issue for it on the fullpage.js forum](https://github.com/alvarotrigo/fullPage.js/issues/2098).

**Comment by alvarotrigo** [comment]
What error you have when executing this?

```javascript
this.$refs.fullpage.build();
this.$refs.fullpage.api.moveSectionDown();
```

**Comment by rikkipitt** [comment]
Hi @alvarotrigo, no error as such. It just seemingly kills the Vue/Vuex state putting the app in a frozen state so to speak.

I tried to use `v-show` but certain panels try to scroll to the previous hidden section after arriving at the one called...
