### ISSUE TITLE
Cannot set property 'wheelOn' of undefined

### ISSUE THREAD

**Issue by rafaelmagalhaes** [alvarotrigo/vue-fullpage.js#50]
updated the plugin to the latest release 0.0.5

and im getting the following error
Cannot set property 'wheelOn' of undefined

i am using nuxt js 

```
import 'fullpage.js/vendors/scrolloverflow.min' // Optional. When using scrollOverflow:true
import VueFullPage from 'vue-fullpage.js'


Vue.use(VueFullPage);
```

nuxt.config.js file 
```
build: {
        plugins: [
            new webpack.ProvidePlugin({
                $: 'jquery',
                jQuery: 'jquery',
                'window.jQuery': 'jquery',
                IScroll: '~/plugins/scrolloverflow.min',

            })
        ]
    }

```

**Comment by alvarotrigo** [comment]
Should't you be using the same path?

```javascript
import 'fullpage.js/vendors/scrolloverflow.min'
``` 

```javascript
                IScroll: 'fullpage.js/vendors/scrolloverflow.min'
```

**Comment by rafaelmagalhaes** [comment]
i tried that but got same error so i downloaded the scrolloverflow from the dev branch but no look too

**Comment by rafaelmagalhaes** [comment]
fixed it i downloaded the scrolloverflow.min file from https://github.com/alvarotrigo/fullPage.js

that seem to fixed the issue

**Comment by alvarotrigo** [comment]
Vue-fullpage.js 0.0.5 also uses the latest fullpage.js version and the latest vendors file.
So it should be exactly the same file? (Unless you go the file from the fullpage.js dev branch)

**Comment by rafaelmagalhaes** [comment]
i think problem is coming from jquery
i removed jquery and IScroll from nuxt.config file and it worked
but if i import scrolloverflow with 
`import 'fullpage.js/vendors/scrolloverflow.min'
`
i get error with jquery not defined

but using the scrolloverflow from  [fullpagejs](https://github.com/alvarotrigo/fullPage.js ) works without jquery

**Comment by alvarotrigo** [comment]
An update on this?
