### ISSUE TITLE
Couldn't get add slide to work

### ISSUE THREAD

**Issue by chrtz** [alvarotrigo/vue-fullpage.js#52]
Regarding to the dynamic changes section in the manual [dynamic changes](https://github.com/alvarotrigo/vue-fullpage.js#dynamic-changes)

I tried to add slides dynamically on click and navigate to it.
(before I tried to show/hide dynamically on click, but this didn't work. With v-if I have to click three times to actually navigate and show the new slide, with v-show the newly added slide was just added below the current section – which is understandable as it can't be dynamically rendered by fullpage this way)

**example:**

```
…
<full-page :options="options" id="fullpage" ref="fullpage">
…
  <div class="section">
    <div class="slide">
      <button @click="addSlide()">
    </div>
  </div>
…
</full-page>
…

methods: {
  addSlide () {
    var slide = document.createElement('div');
    slide.className = 'slide';
    slide.innerHTML = '<p>An awesome new slide </p>';
    document.querySelector('#fullpage').appendChild(slide)
    this.$refs.fullpage.build();
    this.$refs.fullpage.api.moveSlideRight();
  }
},
…
```

So, I'm not rather sure if I'm just doing something completely wrong – OR – if the manual is faulty.
Everything is handled within the same component so far.

The reason is that I get the slide content via a v-for loop on a `@click`.
When I don't hide the slide before – an empty slide would be shown as long as the click method isn't executed.

–––
**current vue.js:** 2.5.17
**current vue-fullpage.js:** 0.0.5
**current OS:** macOS 10.12.6
**current browser:** Chrome 68.0

**Comment by alvarotrigo** [comment]
> I tried to add slides dynamically on click and navigate to it.

What issue are you having then? 
Why is it not working? What do you get instead?

**Comment by chrtz** [comment]
this might take a few days. will edit when done.

**Comment by alvarotrigo** [comment]
@chrtz note an isolated reproduction is not a reproduction of your site, but of the issue itself.
Use empty sections with a single title and no external CSS or JS files to fullPage.js or vue-fullpage.js

**Comment by chrtz** [comment]
Sure, sorry my bad. I meant it will need a while, because I'm busy. Not because I don't know what to do. Still thank you tons.

**Comment by chrtz** [comment]
Beside the fact, that I still don't have a Repo (sorry).
I noticed something that might help.

Few days ago I wanted to manipulate the DOM to add HTML directly to the DOM.
Like the method above to add a slide dynamically. I couldn't make it work – therefore, I asked a round in a Vue dev group.
They told me, this would be bad practice.

Instead add the markup via computed properties and then call a method to implement the rest.
( _the coming links haven't anything to do with FullPage.js – it's just an illustration of we might gonna make this work!_ )
- https://jsfiddle.net/chrtz/eywraw8t/324703/ (trying to manipulate the DOM directly)
- https://jsfiddle.net/wv7d8qbt/ (DOM manipulation by Vue.js)

PS: I noticed something weird. As the approach above doesn't work currently, I just tried to add the content dynamically instead.  I first thought this might belong to another issue (https://github.com/alvarotrigo/vue-fullpage.js/issues/49#issuecomment-417956868)
As as soon as the content is added - the slide isn't scrollable until I resize the browser window.
I tried to call `$refs.fullpage.api.reBuild()` but this didn't work either.

Vue.js and these slides are gonna make me crazy. haha

**Comment by alvarotrigo** [comment]
Working totally fine for me. See the demo here:
https://codepen.io/alvarotrigo/pen/oPGZjO

Also note you can not add a slide on the fullpage.js wrapper. That's made of sections. You should always add the slide on a section.

So your line here is wrong:

```javascript
    document.querySelector('#fullpage').appendChild(slide)
```

**Comment by chrtz** [comment]
Oh you also mentioned it in the fullpage docs: `In order to create a landscape slider within a section, each slide will be defined by default with an element containing the slide class:`
Sorry, I just followed the `how to add a section dynamically` instructions and thought I just could replace `section` with `slide`. So it was clearly my fault.
In the end it makes sense, why the slide was added outside the `#fullpage` wrapper, as it wasn't added to the slide containing section.

Maybe it's just me and my interpretation or the docs should be a little more straightforward. Thank you anyways. Sorry for the inconvenience.

**BTW: the codepen link doesn't work.**

In my case I just wrote my own slide in panel for now, which optically works like a slide.

**Comment by alvarotrigo** [comment]
> Oh you also mentioned it in the fullpage docs: In order to create a landscape slider within a section, each slide will be defined by default with an element containing the slide class:

Where did you get that? "In order to create a landscape slider within a section, each slide will be defined by default with an element containing the slide class" I can't find that anywhere in the docs?

> BTW: the codepen link doesn't work.

Check again (https://codepen.io/alvarotrigo/pen/oPGZjO) it was private.

**Comment by chrtz** [comment]
It's mentioned here: [Required HTML Structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure). In the fullpage.js docs.

And thanks for the link ;)

**Comment by alvarotrigo** [comment]
> Maybe it's just me and my interpretation or the docs should be a little more straightforward. Thank you anyways. Sorry for the inconvenience.

So what's the confusion ?

**Comment by chrtz** [comment]
This information was just missing in the vue-fullpage docs. :)
So I mainly focused on the vue-fullpage docs instead of the "official" ones.
This is where the education gaps came from.

**Comment by alvarotrigo** [comment]
Right I see. Yeah, I can't just duplicate the whole docs again :)

**Comment by chrtz** [comment]
No worries at all. 
Upcoming users will have the issue logs to learn from my faults. :)
