### ISSUE TITLE
Lazyload images doesn't seem to work

### ISSUE THREAD

**Issue by chrtz** [alvarotrigo/vue-fullpage.js#53]
I tried to lazyload images 
`<img src="" data-src="someimage.jpg" alt="some image">`

and in the options `lazyLoading: true` is set.

But in the rendered page just a broken image icon is shown.

EDIT: Actually, I try to lazyload an animated svg, maybe this might be the problem.

2nd EDIT: I tried a jpg – same result.

**Comment by alvarotrigo** [comment]
I'll check it out.

**Comment by alvarotrigo** [comment]
Working as expected as can bee seen here:
https://codepen.io/alvarotrigo/pen/KxmmRg

**Comment by alvarotrigo** [comment]
If you find the way to reproduce your issue I'll re-open the issue.
