### ISSUE TITLE
How to make a link to focus a slide?

### ISSUE THREAD

**Issue by rimonmath** [alvarotrigo/vue-fullpage.js#54]
I want an anchor tag should focus to a slide of a page. And auto active class on scroll.

**Comment by alvarotrigo** [comment]
All you need to know about fullPage.js is detailed on the [fullpage.js docs](https://github.com/alvarotrigo/fullPage.js).

Basically.
Use the anchors option.
Use the anchor in the link. Like you can see on the menu elements in almost all examples.
