### ISSUE TITLE
Nested full-page components

### ISSUE THREAD

**Issue by AntoniyaM** [alvarotrigo/vue-fullpage.js#55]
Hi Alvaro,

first of all great work on the package, thank you!

We're considering to purchase a license for your product, but we're not sure if it completely covers our use case 🤔

Is it possible to have a <full-page> component inside of a <full-page> component? Basically we need a full page scroll on first scroll, then content sliding (or fading) in on second scroll, then another full page scroll on third scroll, and so on.. If this is possible, would you kindly give me some pointers on how to go about such structure/functionality in vue-fullpage?

Thanks in advance!

**Comment by alvarotrigo** [comment]
Your content will always have to be structured in sections within fullPage.js no matter what.

For the fading effect you can take a look at [the fading effect extension](https://alvarotrigo.com/fullPage/extensions/fading-effect.html), that you could activate on an `afterLoad` event and desactivate it again in another.

For the sliding within a section you can take a look at the scrollOverflow option. [Example here](https://alvarotrigo.com/fullPage/examples/scrolling.html).

But you definitely won't be allowed to use a fullpage.js component inside another fullpage.js component. Only a single instance of fullpage.js is allowed.
