### ISSUE TITLE
Cannot read property 'build' of undefined

### ISSUE THREAD

**Issue by philnichols** [alvarotrigo/vue-fullpage.js#57]
Hi, when I run the example here :
https://github.com/alvarotrigo/vue-fullpage.js/tree/master/demos/webpack
Then hit the "Add section" button in the browser I get the following error:
Uncaught TypeError: Cannot read property 'build' of undefined at VueComponent.addSection
Thanks
Phil

**Comment by philnichols** [comment]
Looks like this was due to this requiring the use of the attribute ref="fullpage" on the component element as per your instructions :-)

**Comment by alvarotrigo** [comment]
Glad you solved it! :)
