### ISSUE TITLE
Navigation button not work when my route changed

### ISSUE THREAD

**Issue by maxrisk** [alvarotrigo/vue-fullpage.js#58]
https://codepen.io/maxrisk/pen/mGzzqq
  
Steps:
1. Click 'Go to Bar' link
2. Click 'Fullpage' link
  
Then the navigation button doesn't work

**Comment by alvarotrigo** [comment]
You still using fullPage.js version 3.0.2 as can be seen on the credits of [your vue-fullpage.js file](https://unpkg.com/vue-fullpage.js@0.0.5/dist/vue-fullpage.min.js).

As I said, you'll have to replace the extensions file for the new version 3.0.3 on the node_modules. Then compile the vue-fullpage.js file yourself. 

If you want to avoid the hassle wait a few more days. I'm planning to release 3.0.3 in a few days.

**Comment by alvarotrigo** [comment]
Closed as duplicated of https://github.com/alvarotrigo/vue-fullpage.js/issues/47#issuecomment-422234146

**Comment by maxrisk** [comment]
@alvarotrigo I upgrade to version 3.0.3 in my project, it still have the same issue.

**Comment by alvarotrigo** [comment]
@maxrisk please update to vue-fullpage.js 0.0.6.
Issue should be fixed there.

**Comment by maxrisk** [comment]
@alvarotrigo I upgrade vue-fullpage.js to 0.0.6 then report fullpage is not defined. Do you have this issue?

**Comment by maxrisk** [comment]
It's weird, but I don't know how to reproduce. I just upgrade to 0.0.6 with npm, then my project not work and report `Uncaught ReferenceError: fullpage is not defined`, I'm not familiar with nodejs, but it work when I downgrade to 0.0.5.

**Comment by maxrisk** [comment]
@alvarotrigo It's weird, but I don't know how to reproduce. I just upgrade to 0.0.6 with npm, then my project not work and report `Uncaught ReferenceError: fullpage is not defined`, I'm not familiar with nodejs, but it work when I downgrade to 0.0.5.

**Comment by alvarotrigo** [comment]
@maxrisk just create a codepen or a codesandbox.
