### ISSUE TITLE
Nuxt.js compatibility

### ISSUE THREAD

**Issue by bovas85** [alvarotrigo/vue-fullpage.js#6]
Hi, great work so far.

Have you checked if this works with Nuxt.js / SSR ?

**Comment by alvarotrigo** [comment]
Nop, I never tried those. 
Did you check it? Is it working? 
If not, do you know what's necessary for them to be compatible?

**Comment by bovas85** [comment]
I can't at the moment, travelling to Amsterdam for VueConf :) 
I'll try when I'm back if you haven't got to it yet.

It's basically the mount/install issue where you are looking for the DOM window when it's not there (In server side).

Usually it's fine by setting the plugin to ssr: false but some of them have some gotchas to take care of (which are easy to fix, but would need to be done plugin side, not from the actual client)

**Comment by bovas85** [comment]
Ok I tried but it won't work.

Can you take a look once you have a moment? 
Error:
Failed to mount component: template or render function not defined.

I tried wrapping with no-ssr component, using as a plugin or direct mount from page but all methods to no avail.

**Comment by alvarotrigo** [comment]
Have you tried this?
https://nuxtjs.org/faq/window-document-undefined/

**Comment by bovas85** [comment]
Not that one I guess although using plugin with ssr false or nossr component does the same. I'll try and get back to you

**Comment by FrancisKong** [comment]
`vue-no-ssr` works for me. Here is the code:

```vue
<template>
  <div>
    <no-ssr>
      <full-page>
        <section class="section">
          page1
        </section>
        <section class="section">
          page2
        </section>
      </full-page>
    </no-ssr>
  </div>
</template>

<script>
import Vue from 'vue';
import NoSSR from 'vue-no-ssr';
import fullpageMixin from 'vue-fullpage.js/dist/mixin.min';

if (process.browser) {
  window.$ = require('jquery');
  require('fullpage.js');
  const FullPage = require('vue-fullpage.js');
  Vue.component('full-page', FullPage.default);
}

export default {
  mixins: [fullpageMixin],
  components: { NoSSR },
}
</script>
```

**Comment by Momciloo** [comment]
Hey @FrancisKong, thanks for the example!
Can you tell me what does  default mean in `Vue.component('full-page', FullPage.default);` ?

I am trying to find a way to pass some options to `FullPage`, but with no success. 

Thank you!

**Comment by alvarotrigo** [comment]
@Momciloo have you seen the [provided example](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/demos/demo1/src/DemoApp.vue)?
Or the [stand alone one](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/demos/stand-alone/index.html)?

There you can see how to pass the options. Defualt is empty. {}, Using fullPage.js defaults.

**Comment by Momciloo** [comment]
Hey @alvarotrigo , for some reason, I thought that will not work with this approach, so I didn't even try! 🤯 haha. Thank you! Works.

**Comment by manegame** [comment]
@FrancisKong thanks for the write-up. This worked for me. I did have to import the jquery.fullpage.min.css file extra. Is this expected behaviour?

in `nuxt.config.js`

```
css: [
    '~/assets/style/vendor/jquery.fullpage.min.css'
  ],
```

**Comment by teamgroove** [comment]
Don't mix it!

If you still depend on jquery when you use VueJS, NUXT or even any nodejs-SSR you are doomed to return to the beginning of the learning path. 

Simply don't even try to solve these problems by mixing all these different libs/stacks. Whenever you encounter this kind of problem, you must have taken the wrong path some crossings back from there.
Please get rid of your beloved jquery-solutions/libs when using VueJS. Look for a matching alternative, or write your own.

https://github.com/vuejs/awesome-vue

When NUXT/SSR (no window-object on the server-side) is needed:

https://github.com/nuxt-community/awesome-nuxt

If your chosen VueJS-component doesn't work as NUXT-plugin, just contact the author of the VueJS-comp. and discuss the SSR-incompatibility. There is a way to solve everything. Maybe help and create a PR.

But never mix that stack with Jquery - that is a kind of 'digital blasphemy'.

Forgive me the negative sounding - but you really need to stop that old behaviour and thinking in jquery-libs all over. At least it's bad for your karma :)

I'm a friend of the vue-fullpage.js-solution - it was really great 2 years ago - but still it depends on jquery. 

But there are other solutions in the VueJS/NUXT-context ...

**Comment by alvarotrigo** [comment]
> But there are other solutions in the VueJS/NUXT-context ...

fullPage.js version 3 won't require jQuery, and it is coming this month :) 
No need to look for anything else.

**Comment by teamgroove** [comment]
Wow. Now that is good news! I really appreciate that. I will try to help if there might be issues left with vuejs/nuxt. Thank you! BTW: any other fullpage-solution i know of, still has it's own quirks, bugs and shortcomings - even when SSR is possible (through directives for example)

**Comment by vaso2** [comment]
Hey @alvarotrigo, great job with version 3! Any plans about your vue-fullpage.js wrapper? It still needs jquery which is an additional pain in terms of Nuxt SSR. Thanks!

**Comment by alvarotrigo** [comment]
@vaso2 I'm about to update it to solve a few issues. I'll take the opportunity to use the new fullpage.js version for it too!

**Comment by alvarotrigo** [comment]
Can you verify if you still having this issue with the latest vue-fullpage.js version 0.0.3?

**Comment by vaso2** [comment]
Hey @alvarotrigo! It still does not support SSR. Because of this, it works with Nuxt only using addPlugin with option `ssr: false,` and wrapping everything in 
`<no-ssr> <full-page :options="options" id="fullpage">...`
Because of this, it has load flicker before `mounted` triggers and actually activates Fullpage - before this you'll see the background of previous layer (in my case - black, and fullpage color is orange).
Problem is `window` usage everywhere, which is unavailable on the server. Any plans to adapt it?

**Comment by alvarotrigo** [comment]
@vaso2 I'll have to first take a look at it and understand the issue, but if you can help in any way, please feel free to provide a pull request!

**Comment by alvarotrigo** [comment]
> If you still depend on jquery when you use VueJS, NUXT or even any nodejs-SSR you are doomed to return to the beginning of the learning path.

Quick update. jQuery is no longer required.

**Comment by andy-noir** [comment]
@vaso2  In your `nuxt.config.js` in the plugins array you need to do this: 
```
  plugins: [
    { src: '~/plugins/plugin1.js' },
    { src: '~/plugins/fullpage.js', ssr: false },
    { src: '~/plugins/plugin2.js' },
  ],
```

 Where `fullpage.js` is the name of the file in plugins folder that you have created yourself. It works for me (the FP works), but still in DevTools i get an error: 

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Comment by bovas85** [comment]
@andy-noir make sure you are not rendering stuff that only appears on client side

**Comment by andy-noir** [comment]
@bovas85 ,Hi! 

What do you mean exactly ? Can you elaborate ? Because i am using ssr: false for Vue-FullPage. And i have another problem. In my `index.vue` page i have a few components (basicly each one is a `<section>`) and they are wrapped with Vue-FullPage component. In my attempts  to fix mismatching client and server i have tried to wrap everything with `<no-ssr>` and when i did that my routing refused to work :)

**Comment by vaso2** [comment]
@andy-noir thanks for the example, but that's not the case. I've actually made exactly this thing by creating a custom plugin to manage all stuff. 
BUT `ssr: false` causes mismatch error, adding `<no-ssr>` means huge load flicker (blank screen actually, because initially you'll have nothing inside <fullpage> tag rendered before mount), and using non of this just crashes because of `window` on server

**Comment by alvarotrigo** [comment]
> Hi! How you actually arranged it on your demo site? Markup comes from server already with classes, generated by javascript in fullpage.js like this one `wrapper.className = TABLE_CELL;`

@vaso2 , I'm using a plane HTML page. I'm not using any server side rendering.
In order to prevent the flicker of the content when fullpage.js applies the vertical alignment, I use the classes `fp-table` and `fp-tableCell` from the very beginning as well as the following stylesheets on my own critical stylesheet:

```css
#fullpage,
#app,
.section,
body,
html {
    height: 100%;
}
.fp-tableCell {
    display: table-cell;
    vertical-align: middle;
    width: 100%;
    height: 100%;
}
.section.fp-table {
    display: table;
    table-layout: fixed;
    width: 100%;
}
``` 

This way the 1st section will take 100% of the viewport even before fullpage.js gets initialised, and the content in it, will be vertically aligned:

```html
        <div class="section fp-table active" id="section-1">
            <div class="fp-tableCell">
                <h2>fullpage</h2>
            </div>
        </div>
```

However, this has nothing to do with SSR?

**Comment by alvarotrigo** [comment]
I assume you guys still need a solution for your SSR cases?

**Comment by andypimlett** [comment]
Have a demo site running; no errors or debug being generated, and scrolling shows the DOM is being updated but there is no change in page..

https://nuxt-fullpage.netlify.com/

**Comment by alvarotrigo** [comment]
Transformations on the fullpage elements are working as expected. 
Just use `display:block` in the `<full-page>` element and it will work.

**Comment by Theo-Dlr** [comment]
Hi guys, I have two issues with the server side rendering v.0.0.7. I use vue-fullpage.js as plugin (with `ssr: false`) and when I load or refresh the page via a route that does not use `<fullpage>` `the fullpage is not defined` error message appears and the application is broken (no routing etc). But when I load the page that contains the `<fullpage>` component, the component and the application works fine but the following error message appears "The client-side rendered virtual DOM tree is not matching server-rendered content."
I also tried without ssr: false and with <no-ssr> but nothing seems to works. Thx for your help.

**Comment by Theo-Dlr** [comment]
@andypimlett Can you tell us how did you make it work with nuxt in your demo ?

**Comment by bovas85** [comment]
it does work for me:
https://cambridge-epigenetix.com

**Comment by Theo-Dlr** [comment]
Maybe you have an idea of ​​what I'm doing wrong ?

**Comment by Theo-Dlr** [comment]
Ok thanks you don't use the same package, I will try that one

**Comment by vaso2** [comment]
@bovas85 thanks for the useful link! It has nothing to do with this library (vue-fullpage.js) but it works! Also, maybe @alvarotrigo can get inspiration on how to implement such a thing. 
As I see it, a major difference is that `fullpage-vue` provides a directive, and so it just "does nothing" with `ssr: false` and shows all nested HTML, while Alvaro's solution uses `slot` feature, and so without SSR there is only emptiness

**Comment by bovas85** [comment]
Ah you're right. I think I had tried this one back then and it didn't work while that one did

**Comment by alvarotrigo** [comment]
Documentation improved thanks to @dobromir-hristov.
Version 0.1.0 contains better docs regarding how to use it with Nuxt.js

**Comment by vaso2** [comment]
Oh, it seems there won't be any major progress soon? Well, I've finally published my [nuxt module](https://www.npmjs.com/package/nuxt-fullpage.js) for this. I wrote it half a year ago (in July, looking at my comments above), but I hoped to publish it after fixing that error message in console. It makes the same thing as described in recent docs improvements, just easier to use.

**Comment by bovas85** [comment]
I've starred it

**Comment by alvarotrigo** [comment]
@vaso2 docs were updated regarding the use of nuxt with vue-fullpage. What else you think is necessary? 
I'm totally open to pull requests :)

**Comment by alvarotrigo** [comment]
Any thoughts on this @dobromir-hristov?

Please take your time to reply, I understand we are in holidays season! :)

**Comment by dobromir-hristov** [comment]
Well, the module he made is essentially what the docs state you should do, so I dont see a reason why not to use it 😄 I did not make it because I am just not using Nuxt and did not think of it hehe. Good job mate.

As for making fullpage work in a browserless environment, I tried some stuff, but with no good results, so I am not sure it will be possible. @alvarotrigo will have to say about that.

**Comment by vaso2** [comment]
@alvarotrigo well, I've just submitted my PR, hope it'll be useful. Have nice holidays!:)
