### ISSUE TITLE
No Touch Navigation after Route Change

### ISSUE THREAD

**Issue by MerryMacMapface** [alvarotrigo/vue-fullpage.js#65]
### Description

On sites build with vue js you can only use touch device's swipe-navigation on first route. If you change the route (via vue-router), no touch events are working anymore. - Normal section switching per buttons is still working correctly. On non-touch devices everything is working fine (except on IE/Edge, but that's another issue). You can try it on iOS or in your desktop browser with activated/emulated touch.

### Steps to reproduce it

- [x] create vue js project with vue router and vue jullpage js
- [x] create router-view and some components to switch between per router-view
- [x] components have multiple other components/divs, wrapped by fullpage
- [x] there is only one fullpage working at the same time, due to no keep-alive

It seems, the touch-events/listeners were not correctly destroyed on route-change?

### Versions

"vue-fullpage.js": "0.0.5",
"vue": "2.5.17",
"vue-router": "3.0.1",
Tested on FF-DevEd 64.0b2, Safari 12.0 (Both MacOS 10.13.6),
iPad 5 (iOS 11.1) & 6 (iOS 12), LG V20, Kindle Fire, Samsung Tab (div. Android)

**Comment by alvarotrigo** [comment]
> "vue-fullpage.js": "0.0.5",

Please update to the latest version 0.0.7 and let me know if you still having the issue.

**Comment by MerryMacMapface** [comment]
I'm at the moment not able to update due to dependency-issues (see issue #60).

**Comment by MerryMacMapface** [comment]
The Issue is still the same with vue-fullpage.js 0.0.9.
It would be very time-consuming to put the stuff together, since it's a very modular build.

I got no error, but can't swipe to the next section after route-change via vue-router. Every route has its own fullpage-wrapper. Scrolling sections per command (i.E. fullpage_api.moveTo(1); or fullpage_api.moveSectionUp();) is working just fine. Only the touch gestures seem not to work properly..

**Comment by MerryMacMapface** [comment]
I made a Codesandbox-Script:
https://codesandbox.io/s/2393lnvmwp

**Comment by alvarotrigo** [comment]
The cosesandbox has JS console errors and the fullpage.js effect doesn't even work in it. 
Can you fix that?

**Comment by MerryMacMapface** [comment]
Is there a way to fix this?
Another workaround for me (the project needs to be done soon) would be to disable touch and use another/own touch-swipe event to fire the slider-move. But I can't disable **only** touch - mouse wheel etc. will be disabled too..

**Comment by dobromir-hristov** [comment]
I will look into it in the evening.

**Comment by alvarotrigo** [comment]
I confirm I still having the issue with the latest vue-fullpage.js 0.1.0. 
Reproduction online (also removing the responsiveWidth option)
https://codesandbox.io/s/p3vny25zw7

@dobromir-hristov thanks for your help btw!

**Comment by MerryMacMapface** [comment]
I updated to the latest version (vue-fullpage 0.1.1, vue 2.5.17) and added options-data again:
https://codesandbox.io/s/x90p82x8jz

**Comment by MerryMacMapface** [comment]
Is there maybe a workaround for me to just turn touch off for the moment? I would use another touch-script to call the up/down-methods from fullpage. But when I disable touch, the scrollwheel will be disabled too... The responsiveWidth-option is in use (classes etc) and I can't use it to prevent touch.

**Comment by MerryMacMapface** [comment]
Okay, I guess the problem is a wrong assignment of the wrappers. The fullpage.js-function:

`function addTouchHandler(){
            if(isTouchDevice || isTouch){

                if(options.autoScrolling){
                    $body.removeEventListener(events.touchmove, preventBouncing, {passive: false});
                    $body.addEventListener(events.touchmove, preventBouncing, {passive: false});
                }

                var wrapper = $(WRAPPER_SEL)[0];
                if(wrapper){
                    wrapper.removeEventListener(events.touchstart, touchStartHandler);
                    wrapper.removeEventListener(events.touchmove, touchMoveHandler, {passive: false});

                    wrapper.addEventListener(events.touchstart, touchStartHandler);
                    wrapper.addEventListener(events.touchmove, touchMoveHandler, {passive: false});
                    console.log(wrapper);
                }
            }
        }`

The console.log throws at load and route change the same component - The one you throw away.
The touchstart- and touchmove-events are not added as listeners to the active shown component!

**Comment by bvandorp** [comment]
We have the same issue, no scrolling on touch on mobile when opening a modal. Scrolling and the navigation still work fine. But swiping does nothing. (It does after first pageload and will work until the modal is openend and closed).

Maybe it is not related but I noticed in console that fullpage_api.version says it is using 3.0.2 (while 3.0.4 should be used since we are using 0.1.1).

And we get an error while using the navigation (but it doesn't seem to break something, so maybe its just another issue):
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

Any help will be greatly appreciated. :)

**Comment by bvandorp** [comment]
Is there anyone who knows a possible solution to this issue? Unfortunately the solution MerryMacMapface provided is no solution for the way we experience it.

**Comment by alvarotrigo** [comment]
@bvandorp unfortunately I haven't had the time to look into the issue. 
@dobromir-hristov, @Chiaparini, @ebisbe any idea what might be the issue here?

**Comment by dobromir-hristov** [comment]
@alvarotrigo could it be that when transitioning, there are two full pages in the DOM, thus it attaches the listeners to the first `.fullpage-wrapper` one that it finds?

**Comment by bvandorp** [comment]
@dobromir-hristov Is there any way that I can test this and confirm what you are saying? Or can I do some kind of workaround for this?

**Comment by dobromir-hristov** [comment]
@bvandrop this is internal to Fullpage, and MerryMacMapface lead me to it.

**Comment by alvarotrigo** [comment]
> @alvarotrigo could it be that when transitioning, there are two full pages in the DOM, thus it attaches the listeners to the first .fullpage-wrapper one that it finds?

@dobromir-hristov yeah that could be, but the way fullPage.js is designed wouldn't allow to have multiple instances of fullpage.js in the same page. 

Why doesn't the previous HTML gets removed before initialising fullpage.js again? 
That's what we have to solve.

**Comment by dobromir-hristov** [comment]
I think its because of the transition. The old page is still in the DOM while the new one gets mounted and showed.

**Comment by alvarotrigo** [comment]
If that's the case then the solution can only be worked out from outside fullPage.js:

- Make the transition
- Once the transition finishes, remove the DOM used for the previous route
- Then initialise the component again

As long as you use these styles in your stylesheet, it shouldn't look bad:

```css
#fullpage,
.section,
body,
.fp-tableCell,
html {
    height: 100%
}
```
Assuming #fullpage is your fullpage wrapper and that you use the default selectors for sections and slides.

**Comment by CHEWX** [comment]
Has anyone actually fixed this issue? @bvandorp @alvarotrigo 

Not sure that method applies to Nuxt.

**Comment by alvarotrigo** [comment]
@CHEWX nothing else to add from my last comment :)

**Comment by CHEWX** [comment]
Is there a working code example as this is going to be an issue on every website. Seems a very odd workaround to have to put this on every website.

**Comment by alvarotrigo** [comment]
@CHEWX we didn't find any other solution so far. You can probably code that behaviour in some kind of routine to execute in every site that uses it?

**Comment by CHEWX** [comment]
Do you have a code example? Not entirely sure how to "remove the DOM used for the previous route" in Nuxt. Is that even a thing?

**Comment by alvarotrigo** [comment]
Unfortunately nope

**Comment by Montags24** [comment]
Was this ever actually fixed? I am running into the same issue now.

**Comment by alvarotrigo** [comment]
@Montags24 can you try setting this option on the fullPage.js initalisation?
I assume you use the latest vue-fullpage.js version.

```js
touchWrapper: 'body'
``` 

Or your "app" container (or the equivalent one you use to render your app `<div id="app"></div>`)

```js
touchWrapper: '#app'
```

**Comment by Montags24** [comment]
> @Montags24 can you try setting this option on the fullPage.js initalisation? I assume you use the latest vue-fullpage.js version.
> 
> ```js
> touchWrapper: 'body'
> ```
> 
> Or your "app" container (or the equivalent one you use to render your app `<div id="app"></div>`)
> 
> ```js
> touchWrapper: '#app'
> ```

Do you mind expanding on where this should go? I'm currently looking at the current options that I can send to fullpage.js https://github.com/alvarotrigo/fullPage.js#options and touchWrapper doesn't seem to be one of them.

Thanks

**Comment by alvarotrigo** [comment]
Yeap, that's right, it's an undocumented option.

It goes in the same place as the rest of documented options.

**Comment by Montags24** [comment]
Hi @alvarotrigo. Tried that but didn't have any effect. It's not just on touch navigation. It's also affected on desktop as well. Strange behaviour that I can't pin down. I may record a video later and submit that if that might help?

**Comment by alvarotrigo** [comment]
> Hi @alvarotrigo. Tried that but didn't have any effect. It's not just on touch navigation.

Then, let's open a new issue, as it's not the same one reported here.
I'm able to scroll as expected on the reproduction of this issue 
https://codesandbox.io/s/p3vny25zw7

> I may record a video later and submit that if that might help?

Not much. 
What will help for sure is an isolated reproduction of the issue on codesandbox.
