### ISSUE TITLE
Failed to Compile Error?

### ISSUE THREAD

**Issue by akinhwan** [alvarotrigo/vue-fullpage.js#7]
I am getting the following error on my dev webpack vue project.
I'm installed fullpage.js in addition to vue-fullpage.js via npm, is there any other dependency I am missing here?

./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Can't resolve 'FullPage' in 'C:\Users\Andrew\PROJECTS\portfolio\src'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 15:0-32
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by alvarotrigo** [comment]
See [this topic](https://github.com/alvarotrigo/vue-fullpage.js/issues/4), it might help.

All dependencies are liste din the package.json file. So I don't think that's the issue. 
In fact, you can run the examples to test it yourself.

Get into the vue-fullpage.js folder and do:

```
npm install 
npm run-script demo1
```

**Comment by jawnirock** [comment]
Got the same error! Did what you suggested and now got new errors:

ERROR in ./~/vue-fullpage.js/~/vue-loader/lib/template-compiler?id=data-v-174bdbfa!./~/vue-fullpage.js/~/vue-loader/lib/selector.js?type=template&index=0!./~/vue-fullpage.js/src/FullPage.vue
Module build failed: TypeError: Cannot read property 'transforms' of undefined
    at Object.module.exports (/home/ubuntu/workspace/mda18/node_modules/vue-fullpage.js/node_modules/vue-loader/lib/template-compiler/index.js:60:35)
 @ ./~/vue-fullpage.js/src/FullPage.vue 8:23-148

ERROR in ./~/vue-fullpage.js/~/babel-loader/lib!./~/vue-fullpage.js/~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-fullpage.js/src/FullPage.vue
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (/home/ubuntu/workspace/mda18/node_modules/vue-fullpage.js/node_modules/babel-loader/lib/utils/exists.js:7:25)
    at find (/home/ubuntu/workspace/mda18/node_modules/vue-fullpage.js/node_modules/babel-loader/lib/resolve-rc.js:13:9)
    at Object.module.exports (/home/ubuntu/workspace/mda18/node_modules/vue-fullpage.js/node_modules/babel-loader/lib/index.js:113:132)
 @ ./~/vue-fullpage.js/src/FullPage.vue 5:18-102

**Comment by alvarotrigo** [comment]
Sorry but I can not reproduce your issue. 

```shell
npm install vue-fullpage.js --save-dev
cd node_modules/vue-fullpage.js/
npm install
npm run-script demo1
``` 
I believe the issue is somewhere in your build script rather than in the vue-fullpage.js module itself. 
I would encourage you to ask in some other forum. 

I have no idea why your script is trying to look for things like `vue-loader` in the `vue-fullpage.js` folder instead of in the node_modules one `vue-fullpage.js/node_modules/`.

**Comment by jawnirock** [comment]
I'll look into it, thank you!
It's my first time using Fullpage with vue, but I've been using it for a while in jQuery, your work is truly outstanding

**Comment by akinhwan** [comment]
@alvarotrigo I realized that I had to include two script tags for "jquery.min.js" and "jquery.fullpage.js" in my index.html file. That issue thread you posted from about 20 days ago really helped. I thought maybe this could be mentioned more explicitly in the "Installation" Section of the docs on npm/github page? I thought that I didn't have to include these cdn links if I had npm installed fullPage.js library with its dependencies?

**Comment by alvarotrigo** [comment]
> I realized that I had to include two script tags for "jquery.min.js" and "jquery.fullpage.js" in my index.html file. That issue thread you posted from about 20 days ago really helped. I thought maybe this could be mentioned more explicitly in the "Installation" Section of the docs on npm/github page?

Thanks for the feedback! I've took note of it and will definitely do! 
Although you can always look at the `package.json` file and see it under dependencies ;)
