### ISSUE TITLE
Rolling gently, rolling multiple screens

### ISSUE THREAD

**Issue by dengli1216** [alvarotrigo/vue-fullpage.js#71]
Slide down slightly, but scroll through multiple screens, which makes it impossible to stay in the middle and see the left-right switching effect on the second page. What problems may affect this situation?

**Comment by alvarotrigo** [comment]
Sorry but I don't know what you are talking about.
But it seems your issue is not directly related with the Vue wrapper, therefore I would suggest you to open a new issue on the fullPage.js repository with a different explanation and ideally providing images or videos to illustrate your issue.
