### ISSUE TITLE
Slider was created on the 2 level

### ISSUE THREAD

**Issue by dengli1216** [alvarotrigo/vue-fullpage.js#75]
Horizontal sliders are created in two layers, so that each slider is twice the width of the current screen. When sliding left and right, you can't see the contents of the slider behind：

如图：
![image](https://user-images.githubusercontent.com/23235146/48397556-0feb8900-e759-11e8-858e-a940ae6b6b26.png)

代码如下：
![image](https://user-images.githubusercontent.com/23235146/48397637-5640e800-e759-11e8-83c7-fcaf9a81174e.png)

**Comment by alvarotrigo** [comment]
I can not reproduce your issue on the public codepen:
https://codepen.io/alvarotrigo/pen/zpQmwq

Can you please provide an isolated reproduction of the issue? Perhaps updating the pen to do so?

**Comment by dengli1216** [comment]
I've found the cause of the problem. It's affected by the vue-photo-preview component in the project. Thank you.
