### ISSUE TITLE
Disable scroll listener programmatically without destroy

### ISSUE THREAD

**Issue by yingban** [alvarotrigo/vue-fullpage.js#79]
Hi !

I am using vue-fullpage.js as a navigation component, so it's the same on the whole site.
I would like to know if it's possible to programmatically disable the scroll listener on a certain page, without destroying the fullpage component, and reactivate in another page ? 

Thanks !

**Comment by dobromir-hristov** [comment]
Did you try with `normalScrollElements` ?

**Comment by alvarotrigo** [comment]
@dobromir-hristov thanks for the answer :)

@yingban you can destroy all fullPage.js listeners by calling `fullpage_api.destroy();`.

You get a similar effect with `fullpage.setResponsive(true)`, although in this case the bullets navigation will disappear and anchors will still working.

**Comment by yingban** [comment]
@alvarotrigo, @dobromir-hristov thanks for your reply and sorry for my late reply 

I m gonna try out these solutions.
