### ISSUE TITLE
Scroll not detected/triggered when cursor is over fp-tableCell

### ISSUE THREAD

**Issue by akinhwan** [alvarotrigo/vue-fullpage.js#80]
I have html structured like so 
![screenshot 724](https://user-images.githubusercontent.com/10124722/48980379-1ef60380-f096-11e8-8b7e-45bc8cd57c94.png)

visible at this url
[my portfolio site] (https://akinhwan.github.io/#3)

scrolling doesn't appear to work over this section, either on desktop or mobile. 
scrolling only appears to work when cursor is not intersecting with the div class "fp-tableCell"

I thought it may be because of the z-index, but that didn't work either.

**Comment by dobromir-hristov** [comment]
The issue is on one particular div, not all tableCell's. This leads me to believe something is hogging the scroll event there.

**Comment by alvarotrigo** [comment]
@akinhwan Review your HTML markup. We'd better wait for an isolated reproduction in any case.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
