### ISSUE TITLE
Temporarily disable overflow:hidden while navigating

### ISSUE THREAD

**Issue by bparticle** [alvarotrigo/vue-fullpage.js#85]
I have a question similar to #81. In my case view transitions work well because I'm keeping the full-page scroll alive when navigating (with the built in <keep-alive> component), but this creates another conflict: the javascript from fullpage stays active on the other views which means that scroll is disabled and overflow hidden. Is there a method or an easy way to temporarily disable this safely? I don't want to loose the scroll position and so forth on the fullpage scroll view which currently works great.

**Comment by alvarotrigo** [comment]
Check the fullpage.js documentation regarding the method `setAutoScrolling(false)`

**Comment by bparticle** [comment]
Thanks for the answer, Alvaro. Setting false on setAutoScrolling does indeed solve my problems on the target view, but I want to return to the fullpage view without loosing the scroll position afterwards. Turning it off is a bit jerky (jump to top), and turning it back on does not give me the smooth transitions I am after. I have partially obtained what I want by temporarily removing the inline styles on html and body created by the plugin. It looks and behaves very well, but unfortunately touch actions are disabled on mobile and I can't figure out where to reset that behavior. https://modest-booth-81a2e1.netlify.com/

**Comment by alvarotrigo** [comment]
> but I want to return to the fullpage view without loosing the scroll position afterwards. Turning it off is a bit jerky (jump to top),

I can't reproduce that. It always stays in the same section. 
If you believe this is an issue in fullPage.js please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
