### ISSUE TITLE
Example on the readme.md does not work.

### ISSUE THREAD

**Issue by paraself** [alvarotrigo/vue-fullpage.js#9]
```
import FullPage from 'FullPage';
```
Cannot find module 'FullPage'.

**Comment by alvarotrigo** [comment]
Check the [`demo1`](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/demos/demo1/src/DemoApp.vue) within the `demos` folder. It is working as expected and is using the same logic, just with a different path:

```javascript
 import FullPage from './../../../src/FullPage.vue';
 import fullPageMixin from './../../../src/fullPageMixin';
```

**Comment by paraself** [comment]
Oh thanks, it could be clearer if you can wrap it as a vue plugin.

**Comment by alvarotrigo** [comment]
@paraself could you be more specific? Not quite sure what you mean.

**Comment by alvarotrigo** [comment]
@paraself thanks for that! I'll check it!
