### ISSUE TITLE
afterLoad won't trigger

### ISSUE THREAD

**Issue by eduardoliron** [alvarotrigo/vue-fullpage.js#92]
What am I doing wrong?

I tried it a lot but could not trigger any callback when using Vue.

[https://codepen.io/eduardoliron/pen/XOzLrE](https://codepen.io/eduardoliron/pen/XOzLrE)

**Comment by alvarotrigo** [comment]
As can be seen in the `stand-alone` demo on the demos folder, you should return a function in the data property:

```javascript
 data: function(){
    return {
      options: {
        afterLoad: this.afterLoad,
        scrollBar: false,
        menu: '#menu',
        navigation: true,
        anchors: ['page1', 'page2', 'page3'],
        sectionsColor: ['#41b883', '#ff5f45', '#0798ec', '#fec401', '#1bcee6', '#ee1a59', '#2c3e4f', '#ba5be9', '#b4b8ab']
      }
    }
  },
```

**Comment by alvarotrigo** [comment]
I've updated the [codepen demo](https://codepen.io/alvarotrigo/pen/zpQmwq) so you can also see it working there.

**Comment by eduardoliron** [comment]
Sorry...

It works now.

Thanks!
