### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by amkaah** [alvarotrigo/vue-fullpage.js#93]
hi 
how to section inner div background-image  ?

**Comment by dobromir-hristov** [comment]
Please elaborate. The question is very vague. Example of what you want to achieve would help.

**Comment by alvarotrigo** [comment]
You'd better ask about it somewhere else such as http://stackoverflow.com/ where they'll be able to help you better.
Your problem has nothing to do with fullpage.js. Not directly related.
