### ISSUE TITLE
What's the best way to load dynamic data?

### ISSUE THREAD

**Issue by travbus** [alvarotrigo/vue-fullpage.js#95]
### Description
I have an array of data but I can't it to load properly it just outputs as a list not pages. 

```js
<full-page ref="fullpage"   id="fullpage">
            <div v-for="(val, feedPostsKey) in feedPosts" class="section"  :key="feedPostsKey"  >
                          Loop Content
            </div>
 </full-page>
```

I tried after data is loaded and also in the created function
`this.$refs.fullpage.build()`

I get error 
Cannot read property 'nextElementSibling
If I use static div's it works as it should I'm sure its something simple I"m missing? Thanks!

### Versions 
Chrome, latest version 
###

**Comment by dobromir-hristov** [comment]
Please share how you are fetching those `feedPosts`

**Comment by travbus** [comment]
check out the created function. Steps data is the simular format what i use as feedPosts data. 

https://codepen.io/travis-pancakes/pen/XOGeam?editors=0010

**Comment by travbus** [comment]
I went with this script instead as
https://surmon-china.github.io/vue-awesome-swiper/
