### ISSUE TITLE
[Bug Report] navigation option not working

### ISSUE THREAD

**Issue by ulisses-cruz** [alvarotrigo/vue-fullpage.js#96]
### Versions and Environment
**Vue-fullpage.js:** 0.1.2
**vue:** 2.6.6
**Browser:** 72.0.3626.109
**OS:** Windows 7

### Reproduction Link
https://codesandbox.io/s/xzj9w24mvq

### Expected Behavior
When setting the option `navigation: true`, it should show a navigation bar made up of small circles.

### Actual Behavior
Although, when inspecting the page we can see a div with `id='fp-nav'`, it is not showing in the right place or with the right style.

**Comment by alvarotrigo** [comment]
You are missing the css file.

**Comment by ulisses-cruz** [comment]
@alvarotrigo thank for making me see that.
Just one more question (maybe the answer will prevent me from opening another issue):
why is it that when i set the `navigation` option  to `true` the code creates `<div class='fp-nav'>` 
directly inside `<body>` and not inside `<div class='fullpage-wrapper'>`?

I'm asking because I'm using the `fullpage.js` inside another component (`vuetifyjs tabs component`)
and that will cause me problems.

**Comment by ulisses-cruz** [comment]
Here is how I'm trying to use the library: 
https://codesandbox.io/s/3rmvql1136

You will see that it creates two navbars.

**Comment by alvarotrigo** [comment]
> why is it that when i set the `navigation` option to `true` the code creates `<div class='fp-nav'>`
> **directly inside** `<body>` and not inside `<div class='fullpage-wrapper'>`?

Fixed elements won't work well inside elements using translade3d transformations.
