### ISSUE TITLE
[Bug] parallax extension not getting destroyed properly when navigating to a new route via vue router

### ISSUE THREAD

**Issue by mjwlist** [alvarotrigo/vue-fullpage.js#97]
### Error 
Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined
    at a (vue-fullpage.js?a45e:103)
    at io (vue-fullpage.js?a45e:103)
    at oe (fullpage.parallax.min.js?1c2f:8)
    at window.fp_parallaxExtension.d.destroy (fullpage.parallax.min.js?1c2f:8)
    at HTMLDivElement.re (fullpage.parallax.min.js?1c2f:8)
    at eo (vue-fullpage.js?a45e:103)
    at Object.S.destroy (vue-fullpage.js?a45e:103)
    at VueComponent.destroy (vue-fullpage.js?a45e:206)
    at VueComponent.beforeDestroy (vue-fullpage.js?a45e:227)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1847)

### Reproduction Link
https://codesandbox.io/s/zrn41qnq34
NB: I cannot add the parallax extension in codesandbox but just add it as you see fit and un-comment in index.js.

Github repository if usefull: https://github.com/mjwlist/fullpage-js-issues

### Steps to reproduce
Navigate to /about move around the page. Use the 'Link to home route'. Check the console.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Seems like a bug in vue-fullpage.js. 

Apparently, when calling the destroy function of fullpage.js, there's no section in the DOM with the class `.fp-section.active`. 

@dobromir-hristov any idea why this can be?

**Comment by mjwlist** [comment]
@alvarotrigo Is this likely something that will be addressed in the near future? I have a fairly large site built with vue-full-page.js and the parallax extension that's supposed to be going into production towards the end of March.  We have bought the extension and need to purchase a commercial license for the core library.

**Comment by alvarotrigo** [comment]
> Is this likely something that will be addressed in the near future?

Please [contact me](https://alvarotrigo.com/#contact) and let me know your license key or the email used for the purchase. I'll send you a new updated version of the parallax extension that fixes the issue.

> Could this be considered as a feature enhancement or have you any thoughts on potential workarounds.

The issue regarding the 1st slide anchor is marked as an enhancement. 
If you really need this feature, I can work for a customised version for you for some price. However, you wouldn't be able to update as it won't be included in fullpage.js yet.

> Alternatively does the reset sliders extension help in that it can know it will always be slide index 0 when moving from another section.

Yeap, you'll always land on slide 0 if you use that extension.

**Comment by alvarotrigo** [comment]
I'll close the issue as it seems to be fixed.
