### ISSUE TITLE
Incorrect indexing of slides from afterslideLoad callback

### ISSUE THREAD

**Issue by mjwlist** [alvarotrigo/vue-fullpage.js#98]
### Description
When a section has multiple slides the afterSlideLoad callback returns an incorrect destination.index after navigating from a slide with an index > 0 to the following section,  then navigating back to the initial section. The slide index is always 0 on return despite returning to a slide which should have an index of 1 for example.

### Example
https://codesandbox.io/s/zrn41qnq34

**Comment by alvarotrigo** [comment]
> https://codesandbox.io/s/zrn41qnq34

I can not even scroll to any section.
Can you please provide an isolated reproduction that works?

**Comment by alvarotrigo** [comment]
Oh, I have to click on the text :)

**Comment by alvarotrigo** [comment]
afterslideLoad is never fired when arriving to the section with horizontal slides.
Only when moving horizontally.
