### ISSUE TITLE
First slide of a section does not display the slide anchor in the url

### ISSUE THREAD

**Issue by mjwlist** [alvarotrigo/vue-fullpage.js#99]
### Description
As title. Not sure if this is intended behaviour but would be preferable to always have the current full anchor path displayed in the browser url.

### Example
https://codesandbox.io/s/zrn41qnq34

**Comment by alvarotrigo** [comment]
That's a design decision.
There's already an open issue about it on the fullpage.js repository:
https://github.com/alvarotrigo/fullPage.js/issues/2000

It has been marked as a possible enhancement for the future.
